=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/2007nn.dtd
<!ELEMENT superEntry (orth, entry+)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT entry (mnt_grp, see?, morph_grp, idm_grp?, sense+)>
<!ATTLIST entry n NMTOKEN #IMPLIED>
<!ATTLIST entry pos (nng_s|nng_c|nng_b|np|rt|temp) #REQUIRED>	

<!ELEMENT mnt_grp (cre, mod*, note*, add*)>
<!ELEMENT cre (cre_date, cre_writer, cre_note*)>
<!ELEMENT cre_date (#PCDATA)>
<!ELEMENT cre_writer (#PCDATA)>
<!ELEMENT cre_note (#PCDATA)>
<!ELEMENT mod (mod_date, mod_writer, mod_note*)>
<!ELEMENT mod_date (#PCDATA)>
<!ELEMENT mod_writer (#PCDATA)>
<!ELEMENT mod_note (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT add (#PCDATA)>

<!ELEMENT see (#PCDATA)>

<!ELEMENT morph_grp (var*, str?, org*, symb?, hom?, der*, comp*, metc*, img*)>
<!ELEMENT var (#PCDATA)>
<!ATTLIST var type (xs|xd|xx|abb|lng|spr|etc|temp) #REQUIRED>
<!ELEMENT str (#PCDATA)>
<!ATTLIST str type (N_N|R_N|N_R|R_R|N_Vn|Vn_N|R_Vn|Vn_R|NsN|Vm_N|Am_N|N_S|R_S|V_S|A_S|P_N|P_R|fN_N|N_Nf|fN_Nf|FLW|Ad_N|etc|temp) #REQUIRED>
<!ELEMENT org (#PCDATA)>
<!ATTLIST org lg (si|en|etc|temp) #REQUIRED>
<!ELEMENT symb (#PCDATA)>

<!ELEMENT hom EMPTY>
<!ATTLIST hom exist (yes|temp) #REQUIRED>
<!ELEMENT der (#PCDATA)>
<!ATTLIST der pos (n|v|a|av|temp) #REQUIRED>						
<!ATTLIST der type (suffix|prefix|temp) #REQUIRED>			
<!ELEMENT comp (#PCDATA)>
<!ATTLIST comp pos (n|v|a|av|temp) #REQUIRED>					
<!ATTLIST comp type (suffix|prefix|temp) #REQUIRED>		
<!ELEMENT metc (#PCDATA)>
<!ATTLIST metc pos (n|v|a|av|temp) #REQUIRED>					
<!ATTLIST metc type (suffix|prefix|etc|temp) #REQUIRED>		
<!ELEMENT img (#PCDATA)>
<!ATTLIST img type (xs|xd|xx|xp|temp) #REQUIRED>				

<!ELEMENT idm_grp (idm*)>
<!ELEMENT idm (#PCDATA)>
<!ATTLIST idm type (np|na|nv|da|nc|prv|etc|temp) #REQUIRED>

<!ELEMENT sense (sem_grp, syn_grp)>
<!ATTLIST sense n NMTOKEN #IMPLIED>

<!ELEMENT sem_grp (eg+, trans+, domain*, reg?, con?, curs?, sem_class, nm_sub?, cl_sub?, np_sub*, rel_n*, lr?)>
<!ELEMENT eg (#PCDATA)>
<!ELEMENT trans (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT reg (#PCDATA)>
<!ELEMENT con (#PCDATA)>
<!ELEMENT curs EMPTY>
<!ATTLIST curs type (C|U|R|S|CR|UR|CS|US) #REQUIRED>
<!ELEMENT sem_class (#PCDATA)>
<!ELEMENT nm_sub (#PCDATA)>
<!ELEMENT cl_sub (#PCDATA)>
<!ELEMENT np_sub (#PCDATA)>
<!ATTLIST np_sub type (sem|num|ref) #REQUIRED>
<!ELEMENT rel_n (#PCDATA)>

<!ELEMENT lr (syn*, ant*, hyper*, hypo*, coord*, holo*, mero*, rel*)>
<!ELEMENT syn (#PCDATA)>
<!ATTLIST syn type (perfect|sino|kor|honor|de_honor|under|de_under|spoken|de_spoken|vulgar|de_vulgar|etc|temp) #IMPLIED>
<!ELEMENT ant (#PCDATA)>
<!ATTLIST ant type (compl|grad|dir|conv|etc|temp) #IMPLIED>
<!ELEMENT hyper (#PCDATA)>
<!ELEMENT hypo (#PCDATA)>
<!ELEMENT coord (#PCDATA)>
<!ELEMENT holo (#PCDATA)>
<!ELEMENT mero (#PCDATA)>
<!ELEMENT rel (#PCDATA)>

<!ELEMENT syn_grp (comb_aj*, comb_n*, comb_v*, max_n_str*, sel_rst*, cl*, prt*, av*, ds*, pre_d*, pre_n*, s_n*)>

<!ELEMENT comb_aj (#PCDATA)>
<!ATTLIST comb_aj type (appr|magn|min|temp) #REQUIRED>			
<!ATTLIST comb_aj mod (no) #IMPLIED>
<!ATTLIST comb_aj pred (no) #IMPLIED>

<!ELEMENT comb_n (#PCDATA)>
<!ATTLIST comb_n type (lexfunc|compound|temp) #REQUIRED>		

<!ELEMENT comb_v (form, frame*)>
<!ATTLIST comb_v type (npred_vsup|npred_vsupvar|npred_vpred|npred_vcognate|narg_vcognate|narg_vpred|etc|temp) #REQUIRED>
<!ELEMENT form (#PCDATA)>
<!ATTLIST form vcompound (yes|no|temp) #IMPLIED>					
<!ELEMENT frame (#PCDATA)>

<!ELEMENT max_n_str (#PCDATA)>
<!ELEMENT sel_rst (#PCDATA)>
<!ATTLIST sel_rst arg (X|Y|Z|W|V|temp) #REQUIRED>

<!ELEMENT cl (#PCDATA)>
<!ATTLIST cl type (uni|grp|div|qnt|temp) #REQUIRED>
<!ELEMENT prt (#PCDATA)>
<!ELEMENT av (#PCDATA)>
<!ELEMENT ds (#PCDATA)>

<!ELEMENT pre_d (#PCDATA)>
<!ATTLIST pre_d yn (no) #IMPLIED>
<!ELEMENT pre_n (#PCDATA)>
<!ATTLIST pre_n yn (no) #IMPLIED>
<!ELEMENT s_n (#PCDATA)>
<!ATTLIST s_n yn (no) #IMPLIED>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/차손.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>차손</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/08/08</cre_date>
				<cre_writer>이민우</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/10</mod_date>
				<mod_writer>이민우</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/09/07</mod_date>
				<mod_writer>송근영</mod_writer>
				<mod_note>관련어 항목 추가</mod_note>
				<mod_note>동사결합 정보 수정 및 추가</mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/19</mod_date>
				<mod_writer>박만규</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
		    	<mod_date>2004/12/30</mod_date>
				<mod_writer>장원철</mod_writer>
		        <mod_note></mod_note>
	        </mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">次孫</org>
		
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>우리 집안에 얼마전 ~이 태어났다.</eg>
				<trans>the younger grandson</trans>
				<sem_class>비대칭적친족</sem_class>
				<lr>
					<rel>장손</rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred">
					<form vcompound="no">~이 태어나다</form> <!--송근영 추가-->
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 보다</form> <!--송근영 추가-->
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~이 되다</form> <!-- '~'를 '~이 되다'로 수정(송근영) -->
					<frame>X-이 Y-에게 ~이 되다</frame>
				</comb_v>
				<sel_rst arg="X">인간</sel_rst>
				<sel_rst arg="Y">인간</sel_rst>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/구멍가게.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>구멍가게</orth>
	<entry pos="nng_c">
		<mnt_grp>
			<cre>
				<cre_date>2004/07/03</cre_date>
				<cre_writer>김이정</cre_writer>
				<cre_note>센스 구분 확인 요망</cre_note>
			</cre>
			<mod>
				<mod_date>2004/09/30</mod_date>
				<mod_writer>권오희</mod_writer>
				<mod_note>sem'기업'정도에 해당하는 센스를 하나 더 즉, 센스를 3개로 해야할 듯</mod_note><!--센스3 추가(김)-->
				<mod_note>n_n추가</mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/31</mod_date>
				<mod_writer>권오희</mod_writer>
				<mod_note>센스3의 n_v 기술</mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/05</mod_date>
				<mod_writer>이홍식</mod_writer>
				<mod_note></mod_note>
			</mod>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="etc"></var>
			<str type="N_N">구멍+가게</str>
			<org lg="etc"></org>
		</morph_grp>
		<idm_grp>
			<idm type="etc"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>이 ~에는 물건도 별로 없다.</eg>
				<eg>초등학교 앞 ~에 하교길 아이들이 몰려 든다.</eg>
				<trans>small shop</trans>
				<trans>small store</trans>
				<trans>mom and pop store</trans>
				<domain></domain>
				<sem_class>상업건물</sem_class>
				<lr>
					<syn type="etc"></syn>
					<ant type="etc"></ant>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="min" pred="no">작은 ~</comb_aj>
				<comb_n type="compound">동네 ~</comb_n>
				<comb_n type="compound">~ 주인</comb_n><!--추가(권)-->
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 드나들다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="X"></sel_rst>
				<cl type="uni">곳</cl>
				<cl type="uni">군데</cl>
				<cl type="uni">개</cl>
				<s_n>S는 ~</s_n>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>우리는 영화업을 기존의 ~가 아닌 하나의 산업으로 안정화시켜 나갈 것이다.</eg>
				<eg>한때 ~에 불과했던 벤처기업이 대규모 투자를 결정할 수 있을 만큼 성장했다.</eg>
				<trans>small shop</trans>
				<trans>small store</trans>
				<trans>mom and pop store</trans>
				<domain></domain>
				<sem_class>정도속성값</sem_class>
				<lr>
					<syn type="etc"></syn>
					<ant type="etc"></ant>
					</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr"></comb_aj>
				<comb_n type="compound">~ 규모</comb_n><!--추가(권)-->
				<comb_n type="compound">~ 수준</comb_n>
				<comb_v type="npred_vsup">
					<form vcompound="no">~이다</form>
					<frame>X-이 ~이다</frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="X">산업|기업</sel_rst>
				<cl type="uni"></cl>
				<s_n>S는 ~</s_n>
			</syn_grp>
		</sense>
		<sense n="3">
			<sem_grp>
				<eg>우리 동네 ~는 그래도 빚은 없다.</eg>
				<eg>사이다라도 한 병 사서 ~를 도와주자.</eg>
				<trans>small shop</trans>
				<trans>small store</trans>
				<trans>mom and pop store</trans>
				<domain></domain>
				<sem_class>기업</sem_class>
				<lr>
					<syn type="etc"></syn>
					<ant type="etc"></ant>
					</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr"></comb_aj>
				<comb_n type="compound"></comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 차리다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 운영하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 내다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="X"></sel_rst>
				<cl type="uni">개</cl>
				<s_n>S는 ~</s_n>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/멸종.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">

<superEntry>
	<orth>멸종</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2002/06/11</cre_date>
				<cre_writer>이병규</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/08/13</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/09/01</mod_date>
				<mod_writer>김천학</mod_writer>
				<mod_note>수정없음</mod_note>
			</mod>
			<note>2002/06/11(남길임)</note>
			<note>2002/06/22(이성헌)</note>
			<note>2003/05/23(김미현)의미부류를 '순간적행위'에서 '결과행위'로 수정.멸종이 항상 부정적인 결과만은 아니므로, '부정적결과행위'보다 '결과행위'로 놔두는 것이 타당한 듯 보임.</note>
			<note>단위표현에 '차례' 추가 </note>
			<note>cor_v에 '~하다|되다' 기술</note>
			<note>명사 연어에 '~의 위기' 추가</note>
			<note>2003/08/12(고길수)예문 수정, 연세사전 예문이 그대로 들어있었음</note>
			<note>없어지는 것에서 단위표현이 가능한지 궁금... 삭제함</note>
			<note>기능동사 입력법 수정</note>
			<note>2003/08/13(김미현)</note>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="si">滅種</org>
		
			<hom exist="temp"></hom>
			<der pos="temp" type="temp"></der>
			<comp pos="temp" type="temp"></comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>우리나라의 호랑이는 ~의 위기에 놓여 있다.</eg>
				<trans>extermination of a race</trans>
				<trans>extermination of a stock</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<sem_class>소멸</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="temp"></comb_aj>
				<comb_n type="compound">~의 위기</comb_n>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~을 하다</form>
					<frame>X-이 ~을 하다</frame>
				</comb_v>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~이 되다</form>
					<frame>X-이 ~이 되다</frame>
				</comb_v>
				<!--vcompound: ~하다-->
				<!--vcompound: ~되다-->
				<max_n_str></max_n_str>
				<sel_rst arg="X">생물</sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/국제기구.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>국제기구</orth>
	<entry pos="nng_c">
		<mnt_grp>
			<cre>
				<cre_date>2004/07/30</cre_date>
				<cre_writer>김진형</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2004/0/</mod_date>
				<mod_writer>박진호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/09</mod_date>
				<mod_writer>이홍식</mod_writer>
				<mod_note></mod_note>
			</mod>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="spr">국제 기구</var>
			<str type="R_N">국제+기구</str>
			<org lg="si">國際機構</org>
		</morph_grp>
		<idm_grp>
			<idm type="etc"></idm>
		</idm_grp>
		<sense>
			<sem_grp>
				<eg>우리나라는 여러 ~의 회의를 차례로 개최한다고 한다.</eg>
				<trans>international organization</trans>
				<domain></domain>
				<sem_class>국제기구</sem_class>
				<lr>
					<syn type="etc"></syn>
					<ant type="etc"></ant>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr"></comb_aj>
				<comb_n type="lexfunc"></comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 설립하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~에 가입하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~에서 탈퇴하다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="X"></sel_rst>
				<cl type="uni">개</cl>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/세계.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">

<superEntry>
	<orth>세계</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2000/10/05</cre_date>
				<cre_writer>김종명</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/03/31</mod_date>
				<mod_writer>이민우</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/09/18</mod_date>
				<mod_writer>이민우</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/15</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>센스1 장소를 지역과 인간집단으로 분할;센스3을 속성에서 분야로 수정;맥스엔, 선택제약 정보 추가;수식어 명사에서 N(-의) 삭제;센스4를 추상적대상에서 관계추상적대상으로 수정;맥스엔, 선택제약 정보 추가;수식어 명사에서 N(-의) 삭제</mod_note>
			</mod>
			<note>2003/01/11(이민우)</note>
			<note>2003/03/28(김종명)</note>
			<note>2003/03/31(이민우)</note>
			<add>~가 좁아지다</add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="si">世界</org>
			<hom exist="temp"></hom>
			<der pos="n" type="suffix">~관</der>
			<der pos="n" type="suffix">~적</der>
			<der pos="n" type="suffix">~화</der>
			<der pos="n" type="suffix">~상</der>
			<der pos="n" type="suffix">~사</der>
			<der pos="n" type="suffix">~어</der>
			<der pos="n" type="suffix">~인</der>
			<der pos="n" type="prefix">신~</der>
			<comp pos="n" type="suffix">~주의</comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>그는 ~ 여러 곳을 여행을 다녔다.</eg>
				<trans>world</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<curs type="U"/>
				<sem_class>지역</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~가 넓다</comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="temp">
					<form vcompound="temp"></form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="temp"></sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>~가 점점 하나의 시장이 되고 있다.</eg>
				<eg>우리나라의 눈부신 성장에 ~가 깜짝 놀랐다.</eg>
				<trans>world</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<curs type="U"/>
				<sem_class>인간집단</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr"></comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="temp">
					<form vcompound="temp"></form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="temp"></sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
		<sense n="3">
			<sem_grp>
				<eg>남자들의 ~란 그런 것이다.</eg>
				<trans>society</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<curs type="C"/>
				<sem_class>분야</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~가 다르다</comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 알다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 바꾸다</form>
					<frame></frame>
				</comb_v>
				
				<max_n_str>X-의 ~</max_n_str>
				<max_n_str>X ~</max_n_str>
				<sel_rst arg="X">인간|인간집단|동물</sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n></pre_n>
				<s_n/>
			</syn_grp>
		</sense>
		<sense n="4">
			<sem_grp>
				<eg>우리는 지금 또 다른 차원의 정신 ~를 탐구하고 있다.</eg>
				<trans>world</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<curs type="C"/>
				<sem_class>관계추상적대상</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="temp"></comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="temp">
					<form vcompound="temp"></form>
					<frame></frame>
				</comb_v>
				<max_n_str>X-의 ~</max_n_str>
				<max_n_str>X ~</max_n_str>
				<sel_rst arg="X">무생물|추상적대상</sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n></pre_n>
				<s_n/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/포즈.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">




<superEntry>
	<orth>포즈</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2002/08/23</cre_date>
				<cre_writer>김미현</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/06/18</mod_date>
				<mod_writer>이성헌</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/08/31</mod_date>
				<mod_writer>전미현</mod_writer>
				<mod_note></mod_note>
			</mod>
                        <mod>
                                <mod_date>2005/10/06</mod_date>
                                <mod_writer>박만규</mod_writer>
                                <mod_note></mod_note>
                        </mod>
                        <mod>
				<mod_date>2007/10/03</mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<note>2002/08/23(김미현)늘임표, 쉼표의 뜻으로 쓰인 포즈의 sem은 무엇입니까? 의미부류에 구두점(.,!?)이 어디에 속하는지 모르겠습니다.</note>
			<note>2002/09/09(박동호)일단 '추상적대상'의 하위부류인 '기호'로 하는 것이 좋겠음.2002/10/11(김종명)add정보수정</note>
			<note>2003/05/06(서진숙)</note>
			<note>2003/06/18(이성헌)</note>
			<note>domain추가</note>
			</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="en">pause</org>
		
			<hom exist="yes"/>
			<der pos="temp" type="temp"></der>
			<comp pos="temp" type="temp"></comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>선생님께서는 두 소절 사이에 ~가 있다는 것을 강조하셨다.</eg>
				<eg>악보에 있는 ~를 보지 못하고 연주를 해서 점수가 깎였다.</eg>
				<trans>pause</trans>
				<domain>음악</domain>
				<reg></reg>
				<con></con>
				<sem_class>기호</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="temp"></comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 두다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="temp"></sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2002/08/23</cre_date>
				<cre_writer>김미현</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/06/18</mod_date>
				<mod_writer>이성헌</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/08/31</mod_date>
				<mod_writer>전미현</mod_writer>
				<mod_note></mod_note>
			</mod>
                        <mod>
                                <mod_date>2005/10/06</mod_date>
                                <mod_writer>박만규</mod_writer>
                                <mod_note></mod_note>
                        </mod>
                        <mod>
				<mod_date>2007/10/03</mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<note>2002/09/09(박동호).2002/10/11(김종명)의미부류.동사연어정보수정</note>
			<note>2003/05/06(서진숙)</note>
			<note>2003/06/18(이성헌)sem을 행위에서 '몸짓및동작'으로 수정</note>
			<note>add의 '취하다'를 comb_v로 이동</note>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="en">pose</org>
		
			<hom exist="yes"/>
			<der pos="temp" type="temp"></der>
			<comp pos="temp" type="temp"></comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>그 배우는 카메라 앞에서 매혹적인 ~를 취했다.</eg>
				<eg>나는 사진사의 요구대로 근엄하게 웃는 ~를 취했다.</eg>
				<eg>언니는 재미있는 ~를 좋아했었다.</eg>
				<trans>pose</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<sem_class>몸짓및동작</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~가 아름답다</comb_aj>
				<comb_aj type="appr">~가 멋있다</comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="npred_vpred">
					<form vcompound="no">~를 취하다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="temp"></sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/바지락.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>바지락</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/07/11</cre_date>
				<cre_writer>송인욱</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/13</mod_date>
				<mod_writer>박진호</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/11/06</mod_date>
				<mod_writer>서진숙</mod_writer>
				<mod_note>예문 수정</mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/07</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/22</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note></mod_note>
			</mod>
			<note>2003/10/13(박진호)합성어 추가</note>
			<add>2003/08/08(송인욱)센스1의 동사자유구성으로 '~을 캐다|잡다|키우다|양식하다</add>
			<add>~이 살다|서식하다|죽다' 추가</add>
			<add>2003/08/08(송인욱)센스2의 동사자유구성으로 '~을 먹다' 추가</add>
		</mnt_grp>
		<morph_grp>
		
			<hom exist="yes"/>
			<comp pos="n" type="suffix">~칼국수</comp>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>해녀들은 개펄에서 ~을 한 움큼씩 캐어 왔다.</eg>
				<eg>~은 주로 저 섬 앞바다에 서식하고 있다.</eg>
				<trans>short-necked clam</trans>
				<trans>Mactra veneriformis</trans>
				<sem_class>패류</sem_class>
				<lr>
					<syn type="perfect">바지락조개</syn>
					<syn type="perfect">바지라기</syn>
					<syn type="perfect">바지랑이</syn>
					<hyper>조개</hyper>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="magn">~이 많다</comb_aj>
				<comb_aj type="magn">~이 풍부하다</comb_aj>
				<comb_aj type="min">~이 적다</comb_aj>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 캐다</form>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 잡다</form>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 키우다</form>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 양식하다</form>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~이 살다</form>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~이 서식하다</form>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~이 죽다</form>
				</comb_v>
				<cl type="uni">마리</cl>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>숯불에 구워 먹는 ~의 맛은 정말 일품이다.</eg>
				<eg>~을 날로 먹으면 비브리오 패혈증에 걸릴 위험이 있다.</eg>
				<trans>short-necked clam</trans>
				<trans>Mactra veneriformis</trans>
				<sem_class>자연음식물</sem_class>
				<lr>
					<syn type="perfect">바지락조개</syn>
					<syn type="perfect">바지라기</syn>
					<syn type="perfect">바지랑이</syn>
					<hyper>조개</hyper>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~이 맛있다</comb_aj>
				<comb_aj type="appr">~이 맛없다</comb_aj>
				<comb_aj type="appr">~이 질기다</comb_aj>
				<comb_aj type="appr">~이 부드럽다</comb_aj>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 먹다</form>
				</comb_v>
				<cl type="uni">마리</cl>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/07/11</cre_date>
				<cre_writer>송인욱</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/13</mod_date>
				<mod_writer>박진호</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/11/06</mod_date>
				<mod_writer>서진숙</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/07</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/22</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note>n_v 기술</mod_note>
			</mod>
		</mnt_grp>
		<see>바자</see>
		<morph_grp>
			<var type="xs">바자</var>
		
			<hom exist="yes"/>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>오전에는 그물을 친 해변에서 ~을 잡는 행사가 있다.</eg>
				<trans></trans>
				<sem_class>패류</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 캐다</form>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 잡다</form>
				</comb_v>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/반반.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>반반</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/08/13</cre_date>
				<cre_writer>송인욱</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/15</mod_date>
				<mod_writer>박진호</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/11/06</mod_date>
				<mod_writer>서진숙</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/08</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note></mod_note>
			</mod>
			<note>2003/08/13(송인욱)의미부류 검토 요망</note>
			<note>2003/10/15(박진호)부사적 용법 추가. 센스 세분 가능성 있음</note>
		</mnt_grp>
		<morph_grp>
			<org lg="si">半半</org>
		
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>우리가 그 시험에 통과할 가능성은 ~이었다.</eg>
				<eg>그들은 훔친 물건을 공평하게 ~으로 나누었다.</eg>
				<trans>half-and-half</trans>
				<trans>fifty-fifty</trans>
				<sem_class>부분</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<av>~으로</av>
				<av>~씩</av>
			</syn_grp>
		</sense>
	</entry>
</superEntry>
