=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/2007nn.dtd
<!ELEMENT superEntry (orth, entry+)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT entry (mnt_grp, see?, morph_grp, idm_grp?, sense+)>
<!ATTLIST entry n NMTOKEN #IMPLIED>
<!ATTLIST entry pos (nng_s|nng_c|nng_b|np|rt|temp) #REQUIRED>	

<!ELEMENT mnt_grp (cre, mod*, note*, add*)>
<!ELEMENT cre (cre_date, cre_writer, cre_note*)>
<!ELEMENT cre_date (#PCDATA)>
<!ELEMENT cre_writer (#PCDATA)>
<!ELEMENT cre_note (#PCDATA)>
<!ELEMENT mod (mod_date, mod_writer, mod_note*)>
<!ELEMENT mod_date (#PCDATA)>
<!ELEMENT mod_writer (#PCDATA)>
<!ELEMENT mod_note (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT add (#PCDATA)>

<!ELEMENT see (#PCDATA)>

<!ELEMENT morph_grp (var*, str?, org*, symb?, hom?, der*, comp*, metc*, img*)>
<!ELEMENT var (#PCDATA)>
<!ATTLIST var type (xs|xd|xx|abb|lng|spr|etc|temp) #REQUIRED>
<!ELEMENT str (#PCDATA)>
<!ATTLIST str type (N_N|R_N|N_R|R_R|N_Vn|Vn_N|R_Vn|Vn_R|NsN|Vm_N|Am_N|N_S|R_S|V_S|A_S|P_N|P_R|fN_N|N_Nf|fN_Nf|FLW|Ad_N|etc|temp) #REQUIRED>
<!ELEMENT org (#PCDATA)>
<!ATTLIST org lg (si|en|etc|temp) #REQUIRED>
<!ELEMENT symb (#PCDATA)>

<!ELEMENT hom EMPTY>
<!ATTLIST hom exist (yes|temp) #REQUIRED>
<!ELEMENT der (#PCDATA)>
<!ATTLIST der pos (n|v|a|av|temp) #REQUIRED>						
<!ATTLIST der type (suffix|prefix|temp) #REQUIRED>			
<!ELEMENT comp (#PCDATA)>
<!ATTLIST comp pos (n|v|a|av|temp) #REQUIRED>					
<!ATTLIST comp type (suffix|prefix|temp) #REQUIRED>		
<!ELEMENT metc (#PCDATA)>
<!ATTLIST metc pos (n|v|a|av|temp) #REQUIRED>					
<!ATTLIST metc type (suffix|prefix|etc|temp) #REQUIRED>		
<!ELEMENT img (#PCDATA)>
<!ATTLIST img type (xs|xd|xx|xp|temp) #REQUIRED>				

<!ELEMENT idm_grp (idm*)>
<!ELEMENT idm (#PCDATA)>
<!ATTLIST idm type (np|na|nv|da|nc|prv|etc|temp) #REQUIRED>

<!ELEMENT sense (sem_grp, syn_grp)>
<!ATTLIST sense n NMTOKEN #IMPLIED>

<!ELEMENT sem_grp (eg+, trans+, domain*, reg?, con?, curs?, sem_class, nm_sub?, cl_sub?, np_sub*, rel_n*, lr?)>
<!ELEMENT eg (#PCDATA)>
<!ELEMENT trans (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT reg (#PCDATA)>
<!ELEMENT con (#PCDATA)>
<!ELEMENT curs EMPTY>
<!ATTLIST curs type (C|U|R|S|CR|UR|CS|US) #REQUIRED>
<!ELEMENT sem_class (#PCDATA)>
<!ELEMENT nm_sub (#PCDATA)>
<!ELEMENT cl_sub (#PCDATA)>
<!ELEMENT np_sub (#PCDATA)>
<!ATTLIST np_sub type (sem|num|ref) #REQUIRED>
<!ELEMENT rel_n (#PCDATA)>

<!ELEMENT lr (syn*, ant*, hyper*, hypo*, coord*, holo*, mero*, rel*)>
<!ELEMENT syn (#PCDATA)>
<!ATTLIST syn type (perfect|sino|kor|honor|de_honor|under|de_under|spoken|de_spoken|vulgar|de_vulgar|etc|temp) #IMPLIED>
<!ELEMENT ant (#PCDATA)>
<!ATTLIST ant type (compl|grad|dir|conv|etc|temp) #IMPLIED>
<!ELEMENT hyper (#PCDATA)>
<!ELEMENT hypo (#PCDATA)>
<!ELEMENT coord (#PCDATA)>
<!ELEMENT holo (#PCDATA)>
<!ELEMENT mero (#PCDATA)>
<!ELEMENT rel (#PCDATA)>

<!ELEMENT syn_grp (comb_aj*, comb_n*, comb_v*, max_n_str*, sel_rst*, cl*, prt*, av*, ds*, pre_d*, pre_n*, s_n*)>

<!ELEMENT comb_aj (#PCDATA)>
<!ATTLIST comb_aj type (appr|magn|min|temp) #REQUIRED>			
<!ATTLIST comb_aj mod (no) #IMPLIED>
<!ATTLIST comb_aj pred (no) #IMPLIED>

<!ELEMENT comb_n (#PCDATA)>
<!ATTLIST comb_n type (lexfunc|compound|temp) #REQUIRED>		

<!ELEMENT comb_v (form, frame*)>
<!ATTLIST comb_v type (npred_vsup|npred_vsupvar|npred_vpred|npred_vcognate|narg_vcognate|narg_vpred|etc|temp) #REQUIRED>
<!ELEMENT form (#PCDATA)>
<!ATTLIST form vcompound (yes|no|temp) #IMPLIED>					
<!ELEMENT frame (#PCDATA)>

<!ELEMENT max_n_str (#PCDATA)>
<!ELEMENT sel_rst (#PCDATA)>
<!ATTLIST sel_rst arg (X|Y|Z|W|V|temp) #REQUIRED>

<!ELEMENT cl (#PCDATA)>
<!ATTLIST cl type (uni|grp|div|qnt|temp) #REQUIRED>
<!ELEMENT prt (#PCDATA)>
<!ELEMENT av (#PCDATA)>
<!ELEMENT ds (#PCDATA)>

<!ELEMENT pre_d (#PCDATA)>
<!ATTLIST pre_d yn (no) #IMPLIED>
<!ELEMENT pre_n (#PCDATA)>
<!ATTLIST pre_n yn (no) #IMPLIED>
<!ELEMENT s_n (#PCDATA)>
<!ATTLIST s_n yn (no) #IMPLIED>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/영.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>영</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/11/05</cre_date>
				<cre_writer>최지임</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/11/05</mod_date>
				<mod_writer>최지임</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/09/23</mod_date>
				<mod_writer>박재연</mod_writer>
				<mod_note>을 받다 추가</mod_note>
			</mod>
			<mod>
				<mod_date>2004/10/31</mod_date>
				<mod_writer>나윤희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/29</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>의미부류 추가</mod_note>
				<mod_note>동사결합 정보 추가 및 수정</mod_note>
				<mod_note>논항명사구 정보 추가</mod_note>
				<mod_note>논항 의미정보 추가</mod_note>
				<mod_note>단위표현 정보 추가</mod_note>
				<mod_note>센스2 추가</mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/29</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>센스 2 최대논항구조 삭제</mod_note>
				<mod_note>문형 띄어쓰기 수정</mod_note>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">令</org>
			<hom exist="yes"/>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>그는 거북이의 간을 가져오라는 ~을 받았다.</eg>
				<trans>order</trans>
				<sem_class>명령</sem_class> <!-- 추가 -->
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 거역하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vsupvar"> <!-- 추가함 -->
					<form vcompound="no"></form>
					<frame>X-이 Z-에게 Y-을 ~을 내리다</frame>
					<frame>X-이 Z-에게 S것-을 ~을 내리다</frame>
					<frame>X-이 Z-에게 S라고 ~을 내리다</frame>
				</comb_v>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~을 받다</form>
					<frame>Z-이 X-에게서 Y-을 ~을 받다</frame> <!-- 추가 -->
					<frame>Z-이 X-에게서 S것-을 ~을 받다</frame> <!-- 추가 -->
					<frame>Z-이 X-에게서 S라고 ~을 받다</frame> <!-- S라는 수정 -->
				</comb_v>
				<max_n_str>Z-에대한 X-의 ~</max_n_str> <!-- 추가함 -->
				<sel_rst arg="X">인간</sel_rst>
				<sel_rst arg="Y">행위|계획사건</sel_rst> <!-- 추가함 -->
				<sel_rst arg="Z">인간|인간집단</sel_rst>
				<cl type="uni">번</cl> <!-- 추가함 -->
				<cl type="uni">차례</cl> <!-- 추가함 -->
				<cl type="uni">회</cl> <!-- 추가함 -->
				<s_n>S라는 ~</s_n>
			</syn_grp>
		</sense>
		<sense> <!-- 추가함 -->
			<sem_grp>
				<eg>신하들이 왕에게 ~을 개정할 것을 간언했다.</eg>
				<trans>ordinance</trans>
				<sem_class>법률</sem_class>
				<lr>
					<syn type="etc">법령</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 개정하다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="X">온</sel_rst>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/11/05</cre_date>
				<cre_writer>최지임</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/11/05</mod_date>
				<mod_writer>최지임</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/09/23</mod_date>
				<mod_writer>박재연</mod_writer>
				<mod_note>수정및보충내용없음</mod_note>
			</mod>
			<mod>
				<mod_date>2004/10/31</mod_date>
				<mod_writer>나윤희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/29</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/29</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>수정 없음</mod_note>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">嶺</org>
			<hom exist="yes"/>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>이 ~을 넘으면 해가 저물기 전에 마을에 도착할 수 있다.</eg>
				<trans>high hills</trans>
				<sem_class>고지대</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 넘다</form>
					<frame></frame>
				</comb_v>
				<cl type="uni">개</cl>
			</syn_grp>
		</sense>
	</entry>
	<entry n="3" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/11/05</cre_date>
				<cre_writer>최지임</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/11/05</mod_date>
				<mod_writer>최지임</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/09/23</mod_date>
				<mod_writer>박재연</mod_writer>
				<mod_note>수정및보충내용없음</mod_note>
			</mod>
			<mod>
				<mod_date>2004/10/31</mod_date>
				<mod_writer>나윤희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/29</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>수사??</mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/29</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>수사에서 기술한 표제어, 삭제 요망</mod_note>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">零</org>
			<hom exist="yes"/>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>우리 팀의 전반전 득점은 ~이다.</eg>
				<trans>zero</trans>
				<sem_class>수량속성값</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
			</syn_grp>
		</sense>
	</entry>
	<entry n="4" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/11/05</cre_date>
				<cre_writer>최지임</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/11/05</mod_date>
				<mod_writer>최지임</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/09/23</mod_date>
				<mod_writer>박재연</mod_writer>
				<mod_note>단위명사 명에서 위로 수정</mod_note>
			</mod>
			<mod>
				<mod_date>2004/10/31</mod_date>
				<mod_writer>나윤희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/29</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/29</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>수정 없음</mod_note>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">靈</org>
			<hom exist="yes"/>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>그녀는 떠돌아다니는 ~을 볼 줄 아는 능력이 있다.</eg>
				<trans>spirit</trans>
				<trans>soul</trans>
				<sem_class>상상적인간</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<cl type="uni">위</cl>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/비표.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>비표</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/05/29</cre_date>
				<cre_writer>김미순</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/07/03</mod_date>
				<mod_writer>김진형</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/10/03</mod_date>
				<mod_writer>이민우</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/27</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>동형어 추가</mod_note>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">碑表</org>
		
			<hom exist="yes"/>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>오랜 세월을 견딘 그 비석의 ~는 알아볼 수 없을 정도로 손상되어 있었다.</eg>
				<trans>surface of tombstone</trans>
				<sem_class>구체물의부분</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
			<cl type="uni"></cl>
			</syn_grp>
		</sense>
	</entry>
	<entry pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2004/12/27</cre_date>
				<cre_writer>고길수</cre_writer>
				<cre_note></cre_note>
			</cre>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<org lg="si">&#31061;標</org>
		
			<hom exist="yes"/>
		</morph_grp>
		<idm_grp>
			<idm type="etc"></idm>
		</idm_grp>
		<sense>
			<sem_grp>
				<eg>그 회사는 모든 제품의 용기에 ~를 해둔다.</eg>
				<trans>secret code</trans>
				<domain></domain>
				<sem_class>구체인공물</sem_class> <!-- 검토 필요 -->
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 표시하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred"> <!-- 추가함 -->
					<form vcompound="no">~를 제거하다</form>
					<frame></frame>
				</comb_v>
				<cl type="uni">개</cl>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/치수.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>치수</orth>
	<entry n="1" pos="nng_c">
		<mnt_grp>
			<cre>
				<cre_date>2003/10/07</cre_date>
				<cre_writer>이민우</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/21</mod_date>
				<mod_writer>김종명</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/10/26</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note>add 이동</mod_note>
				<mod_note>형용사 연쇄 추가 기술</mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/22</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note>n_n 정보 추가</mod_note>
				<mod_note>n_v 정보 중 일부 삭제</mod_note>
				<mod_note>동형어 정보 추가</mod_note>
			</mod>
                        <mod>
                                <mod_date>2007/08/16</mod_date>
                                <mod_writer>박진희</mod_writer>
                                <mod_note></mod_note>
                        </mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">_數</org>
		
		    <hom exist="yes"/> <!--추가(미현)-->
        </morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>나는 옷을 맞추기 위해 몸의 ~를 쟀다.</eg>
				<eg>발 ~가 어떻게 됩니까?</eg>
				<trans>size</trans>
				<sem_class>길이단위</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~가 크다</comb_aj>
				<comb_aj type="appr">~가 작다</comb_aj>
				<comb_n type="compound">옷 ~</comb_n>
				<comb_n type="compound">발 ~</comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 재다</form>
					<frame></frame>
				</comb_v>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/10/21</cre_date>
				<cre_writer>김종명</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/21</mod_date>
				<mod_writer>김종명</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/10/26</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note>의미부류 수정</mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/22</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note>max_n 정보 추가</mod_note>
				<mod_note>동형어 정보 추가</mod_note>
				<mod_note>합성어 정보 추가</mod_note>
			</mod>
                        <mod>
                                <mod_date>2007/08/16</mod_date>
                                <mod_writer>박진희</mod_writer>
                                <mod_note></mod_note>
                        </mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">治水</org>
		
		    <hom exist="yes"/> <!--추가(미현)-->
            <comp pos="n" type="prefix">치산~</comp> <!--추가(미현)-->
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>예로부터 치산과 ~를 잘하는 것이 중요하다.</eg>
				<trans>gouverning water</trans>
				<sem_class>지속적활동</sem_class><!--'물리적행위'에서 수정-->
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~를 하다</form>
					<frame>X-이 ~를 하다</frame>
				</comb_v>
				<max_n_str>X-의 ~</max_n_str>
				<sel_rst arg="X">인간</sel_rst>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/피망.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>피망</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/09/16</cre_date>
				<cre_writer>서진숙</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/12</mod_date>
				<mod_writer>서진숙</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/10/06</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note>add를 n_v로 이동;domain(식물) 삭제</mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/01</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/02/15</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note>'채소'로의 센스 추가 기술</mod_note>
			</mod>
			<mod>
				<mod_date>2007/10/03</mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<add>~을 따다</add>
			<add>~이 열리다</add>
		</mnt_grp>
		<morph_grp>
			<org lg="etc">piment</org>
		
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>할머니는 익은 ~부터 따서 광주리에 넣으셨다.</eg>
				<trans>piment</trans>
				<domain></domain>
				<sem_class>열매</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 따다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~이 열리다</form>
					<frame></frame>
				</comb_v>
				<cl type="uni">개</cl>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>샐러드에 ~을 넣으면 고소하게 먹을 수 있다.</eg>
				<trans>piment</trans>
				<domain></domain>
				<sem_class>채소</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
			   <cl type="uni">개</cl>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/서류.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">

<superEntry>
	<orth>서류</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>1999/07/26</cre_date>
				<cre_writer>정유진</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/06/17</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/09/16</mod_date>
				<mod_writer>이민우</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/10</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>센스1 텍스트를 문서로 수정</mod_note>
			</mod>
			<note>2000/07/04</note>
			<note>2003/04/15(이하영)sense1,2 예문수정 및 추가</note>
			<note>2003/06/17(고길수)합성어 정보 표기법 수정</note>
			<note>sense1,2의 동사자유구성 중 일부 삭제, 일부는 add항목으로 옮김</note>
			<note>sense2 단위표현 기입</note>
			<note>센스1,2에 동의어 추가</note>
			<note>센스1의 단위표현에 '통' 추가</note>
			<add>sense1 동사자유구성 '~를 작성하다|읽다|보다' 추가</add>
			<add>sense2 동사자유구성 '~를 집다|찢다|넣다|두다|넘기다|정리하다|분실하다' 추가</add>
			<add>센스1의 동사결합으로 '~를 꾸미다'</add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="si">書類</org>
			<hom exist="temp"></hom>
			<der pos="temp" type="temp"></der>
			<comp pos="n" type="suffix">~가방</comp>
			<comp pos="n" type="suffix">~꽂이</comp>
			<comp pos="n" type="suffix">~장</comp>
			<comp pos="n" type="suffix">~철</comp>
			<comp pos="n" type="suffix">~함</comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>그는 다시 한 번 ~를 꼼꼼이 읽어보았다.</eg>
				<eg>그는 ~를 작성하느라 밤새 한숨도 잠을 자지 못했다.</eg>
				<trans>document</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<curs type="C"/>
				<sem_class>문서</sem_class>
				<lr>
					<syn type="etc">문서</syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="temp"></comb_aj>
				<comb_n type="compound">관계 ~</comb_n>
				<comb_n type="compound">중요 ~</comb_n>
				<comb_n type="compound">기밀 ~</comb_n>
				<comb_n type="compound">증거 ~</comb_n>
				<comb_n type="compound">신청 ~</comb_n>
				<comb_n type="compound">선적 ~</comb_n>
				<comb_n type="compound">~ 양식</comb_n>
				<comb_n type="compound">~ 전형</comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 작성하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 보다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 읽다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="temp"></sel_rst>
				<cl type="uni">개</cl>
				<cl type="uni">장</cl>
				<cl type="uni">통</cl>
				<cl type="grp">묶음</cl>
				<cl type="grp">뭉치</cl>
				<cl type="grp">다발</cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>급한 ~이니 빨리 부장님에게 넘기도록 해라.</eg>
				<eg>사장은 ~를 책상 위로 휙 던져버렸다.</eg>
				<trans>document</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<curs type="C"/>
				<sem_class>텍스트담지물</sem_class>
				<lr>
					<syn type="etc">문서</syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~가 무겁다</comb_aj>
				<comb_aj type="appr">~가 가볍다</comb_aj>
				<comb_aj type="appr">~가 두껍다</comb_aj>
				<comb_aj type="appr">~가 얇다</comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 보관하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 넣다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 두다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 정리하다</form>
					<frame></frame>
				</comb_v>
				<max_n_str></max_n_str>
				<sel_rst arg="temp"></sel_rst>
				<cl type="uni">개</cl>
				<cl type="uni">장</cl>
				<cl type="grp">묶음</cl>
				<cl type="grp">뭉치</cl>
				<cl type="grp">다발</cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/핑퐁.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>핑퐁</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/09/16</cre_date>
				<cre_writer>서진숙</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/12</mod_date>
				<mod_writer>서진숙</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/10/07</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note>센스2 추가;센스1 domain(운동) 삭제;센스1 분류사 추가;센스1 n_v 추가</mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/01</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/10/03</mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="en">ping pong</org>
		
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>중국은 ~에서 타의 추종을 불허하고 있다.</eg>
				<trans>ping pong</trans>
				<domain></domain>
				<sem_class>지속적활동</sem_class>
				<lr>
					<syn type="etc">탁구</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~을 하다</form>
					<frame>X-이 ~을 하다</frame>
				</comb_v>
				<comb_v type="npred_vsupvar">
					<form vcompound="no">~을 치다</form>
					<frame>X-이 ~을 치다</frame>
				</comb_v>
				<sel_rst arg="X">인간</sel_rst>
				<cl type="uni">회</cl>
				<cl type="uni">번</cl>
				<cl type="uni">차례</cl>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>이제 학교와 가정은 거대한 벽을 두고 서로 책임을 떠넘기는 ~ 게임만 하고 있다.</eg>
				<eg>원가 공개를 놓고 당과 정부가 ~을 거듭한지가 오래되었다.</eg>
				<trans>ping pong</trans>
				<domain></domain>
				<sem_class>대칭적행위</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_n type="compound">~ 외교</comb_n>
				<comb_n type="compound">~ 지원</comb_n>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~을 하다</form>
					<frame>X-이 Y-와 ~을 하다</frame>
					<frame>X-와 Y-이 ~을 하다</frame>
				</comb_v>
				<comb_v type="npred_vpred">
					<form vcompound="no">~을 주고받다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vpred">
					<form vcompound="no">~을 거듭하다</form>
					<frame></frame>
				</comb_v>
				<sel_rst arg="X">인간|인간집단</sel_rst>
				<sel_rst arg="Y">인간|인간집단</sel_rst>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/여닫이.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>여닫이</orth>
	<entry n="1" pos="nng_c">
		<mnt_grp>
			<cre>
				<cre_date>2003/11/05</cre_date>
				<cre_writer>최지임</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/11/05</mod_date>
				<mod_writer>최지임</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/09/23</mod_date>
				<mod_writer>박재연</mod_writer>
				<mod_note>수정및보충내용없음</mod_note>
			</mod>
			<mod>
				<mod_date>2004/10/31</mod_date>
				<mod_writer>나윤희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/28</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>복합명사로 수정 후, 내적 구성 정보 추가</mod_note>
				<mod_note>센스1의 의미부류 수정</mod_note>
			</mod>
			<mod>
				<mod_date>2007/09/04</mod_date>
				<mod_writer>권오희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<add>sense2=~를 달다</add>
			<add>sense2=~가 삐걱거리다</add>
		</mnt_grp>
		<morph_grp>
			<str type="V_S">여닫+이</str> <!-- 추가함 -->
		
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>이 문은 손님들이 다니기 편하도록 ~로 되어 있다.</eg>
				<trans>opening and shutting</trans>
				<sem_class>방식속성값</sem_class> <!-- 방식 수정 -->
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>바람이 불자 ~가 삐걱거리기 시작한다.</eg>
				<trans>sliding doors and windows</trans>
				<sem_class>구체물의부분</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~가 낡다</comb_aj>
				<cl type="uni">개</cl>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/습기.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">

<superEntry>
	<orth>습기</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2000/06/26</cre_date>
				<cre_writer>김종명</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/08/08</mod_date>
				<mod_writer>한선혜</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/08/09</mod_date>
				<mod_writer>김천학</mod_writer>
				<mod_note>의미부류수정, add 옮김</mod_note>
			</mod>
			<mod>
				<mod_date>2006/09/15</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>복합어, 동사결합 전반적으로 수정</mod_note>
			</mod>
			<mod>
				<mod_date>2007/09/17</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note></mod_note>
			</mod>
			<note>2001/02/02(최지임)파생어 정보 입력</note>
			<note>2003/07/10(최지임)예문일부수정</note>
			<note>2003/08/08(한선혜)</note>
			<note>관련어 정보 입력</note>
			<note>동사 자유구성 정보 수정</note>
			<note>동사연어구성정보 add에 입력</note>
			<note>동의어 정보 입력</note>
			<note>의미부류검토요망</note>
			<note>의미부류수정</note>
			<note>합성어 정보 입력</note>
			<note>형용사 자유 구성 정보 입력</note>
			<note>형용사자유구성정보 동사연어구성정보에 입력</note>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="si">濕氣</org>
		
			<hom exist="temp"></hom>
			<der pos="n" type="temp"></der>
			<comp pos="n" type="suffix">~계</comp>
			<comp pos="n" type="suffix">~인자</comp>
			<comp pos="n" type="suffix">~역전</comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>지하실 방에 ~가 차서 벽이 눅눅하다.</eg>
				<trans>moisture</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<curs type="U"/>
				<sem_class>기운</sem_class><!--2006/08/09김천학 '무생물'에서 '기운'으로 수정-->
				<lr>
					<syn type="etc">누기</syn>
					<ant type="temp"></ant>
					<rel>건조</rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~가 많다</comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="npred_vsupvar">
					<form vcompound="no">~가 차다</form>
					<frame>X-에 ~가 차다</frame>
					<frame>X-이 ~가 차다</frame>
				</comb_v>
				<comb_v type="npred_vpred">
					<form vcompound="no">~가 배다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vpred">
					<form vcompound="no">~를 제거하다</form>
					<frame></frame>
				</comb_v>
				<max_n_str>X-의 ~</max_n_str>
				<sel_rst arg="X">구체물</sel_rst>
				<cl type="temp"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>
