=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/2007nn.dtd
<!ELEMENT superEntry (orth, entry+)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT entry (mnt_grp, see?, morph_grp, idm_grp?, sense+)>
<!ATTLIST entry n NMTOKEN #IMPLIED>
<!ATTLIST entry pos (nng_s|nng_c|nng_b|np|rt|temp) #REQUIRED>	

<!ELEMENT mnt_grp (cre, mod*, note*, add*)>
<!ELEMENT cre (cre_date, cre_writer, cre_note*)>
<!ELEMENT cre_date (#PCDATA)>
<!ELEMENT cre_writer (#PCDATA)>
<!ELEMENT cre_note (#PCDATA)>
<!ELEMENT mod (mod_date, mod_writer, mod_note*)>
<!ELEMENT mod_date (#PCDATA)>
<!ELEMENT mod_writer (#PCDATA)>
<!ELEMENT mod_note (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT add (#PCDATA)>

<!ELEMENT see (#PCDATA)>

<!ELEMENT morph_grp (var*, str?, org*, symb?, hom?, der*, comp*, metc*, img*)>
<!ELEMENT var (#PCDATA)>
<!ATTLIST var type (xs|xd|xx|abb|lng|spr|etc|temp) #REQUIRED>
<!ELEMENT str (#PCDATA)>
<!ATTLIST str type (N_N|R_N|N_R|R_R|N_Vn|Vn_N|R_Vn|Vn_R|NsN|Vm_N|Am_N|N_S|R_S|V_S|A_S|P_N|P_R|fN_N|N_Nf|fN_Nf|FLW|Ad_N|etc|temp) #REQUIRED>
<!ELEMENT org (#PCDATA)>
<!ATTLIST org lg (si|en|etc|temp) #REQUIRED>
<!ELEMENT symb (#PCDATA)>

<!ELEMENT hom EMPTY>
<!ATTLIST hom exist (yes|temp) #REQUIRED>
<!ELEMENT der (#PCDATA)>
<!ATTLIST der pos (n|v|a|av|temp) #REQUIRED>						
<!ATTLIST der type (suffix|prefix|temp) #REQUIRED>			
<!ELEMENT comp (#PCDATA)>
<!ATTLIST comp pos (n|v|a|av|temp) #REQUIRED>					
<!ATTLIST comp type (suffix|prefix|temp) #REQUIRED>		
<!ELEMENT metc (#PCDATA)>
<!ATTLIST metc pos (n|v|a|av|temp) #REQUIRED>					
<!ATTLIST metc type (suffix|prefix|etc|temp) #REQUIRED>		
<!ELEMENT img (#PCDATA)>
<!ATTLIST img type (xs|xd|xx|xp|temp) #REQUIRED>				

<!ELEMENT idm_grp (idm*)>
<!ELEMENT idm (#PCDATA)>
<!ATTLIST idm type (np|na|nv|da|nc|prv|etc|temp) #REQUIRED>

<!ELEMENT sense (sem_grp, syn_grp)>
<!ATTLIST sense n NMTOKEN #IMPLIED>

<!ELEMENT sem_grp (eg+, trans+, domain*, reg?, con?, curs?, sem_class, nm_sub?, cl_sub?, np_sub*, rel_n*, lr?)>
<!ELEMENT eg (#PCDATA)>
<!ELEMENT trans (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT reg (#PCDATA)>
<!ELEMENT con (#PCDATA)>
<!ELEMENT curs EMPTY>
<!ATTLIST curs type (C|U|R|S|CR|UR|CS|US) #REQUIRED>
<!ELEMENT sem_class (#PCDATA)>
<!ELEMENT nm_sub (#PCDATA)>
<!ELEMENT cl_sub (#PCDATA)>
<!ELEMENT np_sub (#PCDATA)>
<!ATTLIST np_sub type (sem|num|ref) #REQUIRED>
<!ELEMENT rel_n (#PCDATA)>

<!ELEMENT lr (syn*, ant*, hyper*, hypo*, coord*, holo*, mero*, rel*)>
<!ELEMENT syn (#PCDATA)>
<!ATTLIST syn type (perfect|sino|kor|honor|de_honor|under|de_under|spoken|de_spoken|vulgar|de_vulgar|etc|temp) #IMPLIED>
<!ELEMENT ant (#PCDATA)>
<!ATTLIST ant type (compl|grad|dir|conv|etc|temp) #IMPLIED>
<!ELEMENT hyper (#PCDATA)>
<!ELEMENT hypo (#PCDATA)>
<!ELEMENT coord (#PCDATA)>
<!ELEMENT holo (#PCDATA)>
<!ELEMENT mero (#PCDATA)>
<!ELEMENT rel (#PCDATA)>

<!ELEMENT syn_grp (comb_aj*, comb_n*, comb_v*, max_n_str*, sel_rst*, cl*, prt*, av*, ds*, pre_d*, pre_n*, s_n*)>

<!ELEMENT comb_aj (#PCDATA)>
<!ATTLIST comb_aj type (appr|magn|min|temp) #REQUIRED>			
<!ATTLIST comb_aj mod (no) #IMPLIED>
<!ATTLIST comb_aj pred (no) #IMPLIED>

<!ELEMENT comb_n (#PCDATA)>
<!ATTLIST comb_n type (lexfunc|compound|temp) #REQUIRED>		

<!ELEMENT comb_v (form, frame*)>
<!ATTLIST comb_v type (npred_vsup|npred_vsupvar|npred_vpred|npred_vcognate|narg_vcognate|narg_vpred|etc|temp) #REQUIRED>
<!ELEMENT form (#PCDATA)>
<!ATTLIST form vcompound (yes|no|temp) #IMPLIED>					
<!ELEMENT frame (#PCDATA)>

<!ELEMENT max_n_str (#PCDATA)>
<!ELEMENT sel_rst (#PCDATA)>
<!ATTLIST sel_rst arg (X|Y|Z|W|V|temp) #REQUIRED>

<!ELEMENT cl (#PCDATA)>
<!ATTLIST cl type (uni|grp|div|qnt|temp) #REQUIRED>
<!ELEMENT prt (#PCDATA)>
<!ELEMENT av (#PCDATA)>
<!ELEMENT ds (#PCDATA)>

<!ELEMENT pre_d (#PCDATA)>
<!ATTLIST pre_d yn (no) #IMPLIED>
<!ELEMENT pre_n (#PCDATA)>
<!ATTLIST pre_n yn (no) #IMPLIED>
<!ELEMENT s_n (#PCDATA)>
<!ATTLIST s_n yn (no) #IMPLIED>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/빛.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>빛</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2001/07/28</cre_date>
				<cre_writer>차준경</cre_writer>
			</cre>
			<mod>
				<mod_date>2001/07/31</mod_date>
				<mod_writer>차준경강범모</mod_writer>
				<mod_note>일차교정</mod_note>
			</mod>
			<mod>
				<mod_date>2001/08/03</mod_date>
				<mod_writer>차준경</mod_writer>
				<mod_note>이차교정</mod_note>
			</mod>
			<mod>
				<mod_date>2003/03/22</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>센스1의 예문 수정</mod_note>
				<mod_note>의미부류 정보 수정</mod_note>
				<mod_note>단위표현 정보 추가</mod_note>
				<mod_note>comb_aj에 '환하다|눈부시다' 추가</mod_note>
				<mod_note>센스1의 comb_v 정보를 add로 수정</mod_note>
				<mod_note>센스1의 명사연어를 add로 수정</mod_note>
				<mod_note>센스2에 단위표현 추가</mod_note>
				<mod_note>센스2의 형용사자유구성 정보 추가</mod_note>
				<mod_note>comb_v 정보 추가</mod_note>
				<mod_note>comb_v의 '바래다'는 add로 수정</mod_note>
				<mod_note>센스3의 의미부류를 '속성'에서 '태도'로 수정</mod_note>
				<mod_note>센스3의 comb_aj에 '역력하다|뚜렷하다' 추가</mod_note>
				<mod_note>센스3에 comb_v 정보 추가</mod_note>
				<mod_note>add에 센스3의 동사정보 추가</mod_note>
				<mod_note>센스3에 pre_s 정보 추가</mod_note>
				<mod_note>센스4 추가</mod_note>
			</mod>
			<mod>
				<mod_date>2003/04/07</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>센스2의 단위표현에서 '개' 삭제</mod_note>
				<mod_note>센스4에 동의어 추가</mod_note>
				<mod_note>센스7에 동의어 추가</mod_note>
				<mod_note>센스1의 단위표현을 '부분'에서 '양'로 수정</mod_note>
			</mod>
			<mod>
				<mod_date>2003/05/15</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>2003/05/15(고길수)센스1에 magn 정보 추가</mod_note>
				<mod_note>센스2에 단위표현 추가</mod_note>
				<mod_note>센스5를 센스3으로 수정</mod_note>
				<mod_note>센스5, 6에 pre_s 정보 추가</mod_note>
			</mod>
			<mod>
				<mod_date>2004/09/21</mod_date>
				<mod_writer>목정수</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/19</mod_date>
				<mod_writer>이성헌</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/27</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>센스1,2,3에 논항명사구, 논항 의미정보 추가</mod_note>
				<mod_note>센스3,4의 동사결합 정보 수정</mod_note>
			</mod>
			<add>센스2의 동사결합으로 '~이 바래다|나다,~을 내다' 추가</add>
			<add>센스5의 동사결합으로 '~이 감돌다'</add>
			<add>센스5의 명사구로 '긴장의 ~'</add>
			<add>센스1의 명사구 '~(의) 줄기,~의 굴절'</add>
			<add>센스4의 동사결합으로 '~이 깊어지다|달라지다,~을 감추다' 추가</add>
			<add>센스7의 동사결합으로 '~을 주다,~이 되다' 추가</add>
			<add>센스1의 동사결합 '~을 비추다|발하다|내다,~이 환하다|들다|나다'</add>
			<add>센스6의 동사결합으로 '~을 발하다|띠다|내다,~이 나다'</add>
		</mnt_grp>
		<morph_grp>
		
			<comp pos="n" type="suffix">~살</comp>
			<comp pos="n" type="prefix">별~</comp>
			<comp pos="n" type="prefix">달~</comp>
			<comp pos="v" type="suffix">~나다</comp>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>아침해가 떠오르면 방안으로 환한 ~이 쏟아져 들어왔다.</eg>
				<trans>light</trans>
				<curs type="U"/>
				<sem_class>빛</sem_class>
				<lr>
					<syn>광선</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~이 밝다</comb_aj>
				<comb_aj type="appr">~이 희미하다</comb_aj>
				<comb_aj type="appr">~이 환하다</comb_aj>
				<comb_aj type="appr">~이 눈부시다</comb_aj>
				<comb_aj type="magn">~이 강하다</comb_aj>
				<comb_aj type="magn">~이 강렬하다</comb_aj>
				<comb_aj type="magn">~이 약하다</comb_aj>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 비추다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 발하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 내다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~이 들다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- 추가함, 단 기능동사 변이형이 아닌지 검토 필요 -->
					<form vcompound="no">~이 나다</form>
					<frame></frame>
				</comb_v>
				<max_n_str>X-의 ~</max_n_str> <!-- 추가함 -->
				<sel_rst arg="X">천체|조명기구</sel_rst> <!-- 추가함 -->
				<cl type="qnt">줄기</cl>
				<cl type="qnt">가닥</cl>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>옷을 오래 입어서 ~이 바래졌다.</eg>
				<trans>color</trans>
				<trans>hue</trans>
				<trans>tint</trans>
				<trans>shade</trans>
				<curs type="U"/>
				<sem_class>속성</sem_class>
				<lr>
					<syn type="etc">색깔</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~이 환하다</comb_aj>
				<comb_aj type="appr">~이 파랗다</comb_aj>
				<comb_aj type="appr">~이 푸르다</comb_aj>
				<comb_aj type="appr">~이 화려하다</comb_aj>
				<comb_aj type="appr">~이 칙칙하다</comb_aj>
				<comb_v type="narg_vpred"> <!-- 추가함 -->
					<form vcompound="no">~이 바래다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred"> <!-- 추가함 -->
					<form vcompound="no">~이 나다</form>
					<frame></frame>
				</comb_v>
				<max_n_str>X-의 ~</max_n_str> <!-- 추가함 -->
				<sel_rst arg="X">구체물|장소</sel_rst> <!-- 추가함 -->
				<cl type="uni">개</cl>
				<cl type="uni">가지</cl>
			</syn_grp>
		</sense>
		<sense n="3">
			<sem_grp>
				<eg>그의 시계에 박힌 보석들은 찬란한 ~을 내뿜고 있었다.</eg>
				<eg>바닥을 몇 번 문질렀더니 번쩍번쩍 ~이 나기 시작했다.</eg>
				<eg>내가 나타나자 그의 눈에서는 ~으로 번뜩였다.</eg>
				<trans>sparkle</trans>
				<sem_class>빛</sem_class>
				<lr>
					<syn type="etc">광채</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">~이 찬란하다</comb_aj>
				<comb_v type="npred_vpred"> <!-- narg_vpred 수정 -->
					<form>~을 내다</form>
					<frame>X-이 ~을 내다</frame> <!-- 추가 -->
				</comb_v>
				<comb_v type="npred_vpred"> <!-- narg_vpred 수정 -->
					<form>~을 띠다</form>
					<frame>X-이 ~을 띠다</frame> <!-- 추가 -->
				</comb_v>
				<comb_v type="npred_vsupvar"> <!-- narg_vpred 수정 -->
					<form>~이 나다</form>
					<frame>X-이 ~이 나다</frame> <!-- 추가 -->
				</comb_v>
				<max_n_str>X-의 ~</max_n_str> <!-- 추가함 -->
				<sel_rst arg="X">구체물</sel_rst> <!-- 추가함 -->
				<cl type="qnt">줄기</cl>
				<cl type="qnt">가닥</cl>
			</syn_grp>
		</sense>
		<sense n="4">
			<sem_grp>
				<eg>아들이 상을 타서 엄마가 기쁜 ~을 감추지 못했다.</eg>
				<trans>look</trans>
				<curs type="U"/>
				<sem_class>기색</sem_class> <!-- 태도 수정 -->
				<lr>
					<syn type="etc">안색</syn>
					<syn type="etc">태도</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">기쁜 ~</comb_aj>
				<comb_aj type="appr">난처한 ~</comb_aj>
				<comb_aj type="appr">걱정스러운 ~</comb_aj>
				<comb_aj type="appr">~이 역력하다</comb_aj>
				<comb_aj type="appr">~이 뚜렷하다</comb_aj>
				<comb_n type="compound">경계의 ~</comb_n>
				<comb_n type="compound">실망의 ~</comb_n>
				<comb_n type="compound">우려의 ~</comb_n>
				<comb_v type="npred_vpred"> <!-- narg_vpred 수정 -->
					<form>~을 보이다</form>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- narg_vpred 수정 -->
					<form>~을 띠다</form>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- narg_vpred 수정 -->
					<form>~을 내다</form>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- narg_vpred 수정 -->
					<form>~이 보이다</form>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- narg_vpred 수정 -->
					<form>~이 나타나다</form>
				</comb_v>
				<s_n>S는 ~</s_n> <!-- 수식어 성분이 필수적으로 요구되는 듯 -->
			</syn_grp>
		</sense>
		<sense n="5">
			<sem_grp>
				<eg>순간 교실에는 긴장의 ~이 감돌았다.</eg>
				<trans>atmosphere</trans>
				<sem_class>현상</sem_class> <!-- 속성 수정 -->
				<lr>
					<syn type="etc">분위기</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr">쓸쓸한 ~</comb_aj>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~이 감돌다</form>
					<frame></frame>
				</comb_v>
				<s_n>S는 ~</s_n> <!-- 수식어 성분이 필수적인 듯 -->
			</syn_grp>
		</sense>
		<sense n="6">
			<sem_grp>
				<eg>그의 작품은 사람을 매료하는 독특한 ~을 발한다.</eg>
				<trans>splendor</trans>
				<trans>brilliance</trans>
				<sem_class>속성값</sem_class> <!-- 능력 수정 -->
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 발하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="npred_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 뿜다</form>
					<frame></frame>
				</comb_v>
				<s_n>S는 ~</s_n> <!-- 수식어 성분 필수적인 듯 -->
			</syn_grp>
		</sense>
		<sense n="7">
			<sem_grp>
				<eg>희망의 ~이 밝아오고 있으니 모두 열심히 일을 합시다.</eg>
				<eg>그는 암울한 시대에 민중들에게 힘과 ~을 주었다.</eg>
				<trans>hope</trans>
				<trans>bright future</trans>
				<curs type="U"/>
				<sem_class>추상적대상</sem_class>
				<lr>
					<syn type="etc">희망</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_n type="compound">희망의 ~</comb_n>
				<comb_v type="narg_vpred"> <!-- 추가함 -->
					<form vcompound="no">~을 주다</form>
					<frame></frame>
				</comb_v>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/선고.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">

<superEntry>
	<orth>선고</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2002/05/24</cre_date>
				<cre_writer>이지영</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/06/18</mod_date>
				<mod_writer>목정수</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/10/10</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/10/31</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note>'분' 삭제</mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/12</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>맥스엔, 선택제약 정보 추가</mod_note>
			</mod>
			<note>2002/10/14(박진호)</note>
			<note>2003/05/21(김미순)</note>
			<note>2003/06/18(목정수)</note>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="si">先考</org>
			<hom exist="yes"/>
			<der pos="temp" type="temp"></der>
			<comp pos="temp" type="temp"></comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>~께서는 우리를 늘 사랑으로 감싸셨습니다.</eg>
				<trans>deceased father</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<sem_class>비대칭적친족</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="temp"></comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="temp">
					<form vcompound="temp"></form>
					<frame></frame>
				</comb_v>
				<max_n_str>X-의 ~</max_n_str>
				<max_n_str>X ~</max_n_str>
				<sel_rst arg="X">인간</sel_rst>
				<cl type="uni"></cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n/>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2002/05/24</cre_date>
				<cre_writer>이지영</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2003/06/18</mod_date>
				<mod_writer>목정수</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/10/10</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/10/31</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note>센스1,2 s_n 삭제;센스1,2 n_v, 최대논항구조 수정</mod_note>
			</mod>
			<mod>
				<mod_date>2007/08/12</mod_date>
				<mod_writer>고길수</mod_writer>
				<mod_note>센스1의 프레임 정보의 'S다는' 수정;보문 논항 추가;'내리다' 유형값 수정, 프레임 정보 추가;맥스엔 수정 및 추가;선택제약 정보 수정;센스2의 전문영역에서 법률 삭제;프레임 정보의 'S라는' 수정;'받다'에 조사 변이형 추가;'내리다' 유형값 수정, 프레임 정보 추가;맥스엔 보완;선택제약 정보 수정</mod_note>
			</mod>
			<note>2002/10/14(박진호)</note>
			<note>2003/05/21(김미순)sense 1 comb_v에서 '~를 받다' 삭제</note>
			<note>2003/06/18(목정수)cor_v에 받다추가</note>
			<note>comb_v에서 '~를 받다' 삭제</note>
			<note>sel_res 수정</note>
			<note>sense 2 예문수정</note>
			<note>supv 수정 '~를 받다' 구문 추가</note>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="temp"></var>
			<str type="temp"></str>
			<org lg="si">宣告</org>
			<hom exist="yes"/>
			<der pos="temp" type="temp"></der>
			<comp pos="temp" type="temp"></comp>
			<metc pos="temp" type="temp"></metc>
			<img type="temp"></img>
		</morph_grp>
		<idm_grp>
			<idm type="temp"></idm>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>그는 의사로부터 시한부 ~를 받았다.</eg>
				<trans>pronouncement</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<sem_class>보고제안</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="temp"></comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~를 하다</form>
					<frame>X-이 Z-에게 Y-을 ~를 하다</frame>
					<frame>X-이 Z-에게 S것-을 ~를 하다</frame>
					<frame>X-이 Z-에게 S다고 ~를 하다</frame>
					<frame>X-이 Z-에게 S라고 ~를 하다</frame>
				</comb_v>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~가 되다</form>
					<frame>Z-에게 Y-이 ~가 되다</frame>
					<frame>Z-에게 S것-이 ~가 되다</frame>
					<frame>Z-에게 S다고 ~가 되다</frame>
					<frame>Z-에게 S라고 ~가 되다</frame>
				</comb_v>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~를 받다</form>
					<frame>Z-이 X-로부터 Y-을 ~를 받다</frame>
					<frame>Z-이 X-로부터 S것-을 ~를 받다</frame>
					<frame>Z-이 X-로부터 S다고 ~를 받다</frame>
					<frame>Z-이 X-로부터 S라고 ~를 받다</frame>
					<frame>Z-이 X-에게서 Y-을 ~를 받다</frame>
					<frame>Z-이 X-에게서 S것-을 ~를 받다</frame>
					<frame>Z-이 X-에게서 S다고 ~를 받다</frame>
					<frame>Z-이 X-에게서 S라고 ~를 받다</frame>
					<frame>Z-이 X-에게 Y-을 ~를 받다</frame>
					<frame>Z-이 X-에게 S것-을 ~를 받다</frame>
					<frame>Z-이 X-에게 S다고 ~를 받다</frame>
					<frame>Z-이 X-에게 S라고 ~를 받다</frame>
				</comb_v>
				<comb_v type="npred_vsupvar">
					<form vcompound="no">~를 내리다</form>
					<frame>X-이 Z-에게 Y-을 ~를 내리다</frame>
					<frame>X-이 Z-에게 S것-을 ~를 내리다</frame>
					<frame>X-이 Z-에게 S다고 ~를 내리다</frame>
					<frame>X-이 Z-에게 S라고 ~를 내리다</frame>
				</comb_v>
				<!--vcompound: ~하다-->
				<!--vcompound: ~되다-->
				<!--vcompound: ~받다-->
				<max_n_str>X-의 Z-에대한 Y ~</max_n_str>
				<max_n_str>X-의 Z-에대한 S다는 ~</max_n_str>
				<max_n_str>X-의 Z-에대한 S라는 ~</max_n_str>
				<max_n_str>X-의 Y ~</max_n_str>
				<max_n_str>X-의 S다는 ~</max_n_str>
				<max_n_str>X-의 S라는 ~</max_n_str>
				<max_n_str>Z-에대한 Y ~</max_n_str>
				<max_n_str>Z-에대한 S다는 ~</max_n_str>
				<max_n_str>Z-에대한 S라는 ~</max_n_str>
				<max_n_str>X-의 ~</max_n_str>
				<max_n_str>Y ~</max_n_str>
				<max_n_str>S다는 ~</max_n_str>
				<max_n_str>S라는 ~</max_n_str>
				<sel_rst arg="X">직업인간</sel_rst>
				<sel_rst arg="Y">질병및증세|행위</sel_rst>
				<sel_rst arg="Z">인간|일시적집단</sel_rst>
				<cl type="uni">번</cl>
				<cl type="uni">회</cl>
				<cl type="uni">차례</cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n></s_n>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>피고는 판사로부터 5년 징역의 ~를 받았다.</eg>
				<trans>sentence</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				<sem_class>명령</sem_class>
				<lr>
					<syn type="temp"></syn>
					<ant type="temp"></ant>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="temp"></comb_aj>
				<comb_n type="temp"></comb_n>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~를 하다</form>
					<frame>X-이 Z-에게 W-에대해서 Y-을 ~를 하다</frame>
					<frame>X-이 Z-에게 W-에대해서 S라고 ~를 하다</frame>
				</comb_v>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~가 되다</form>
					<frame>Z-에게 Y-이 ~가 되다</frame>
					<frame>Z-에게 S라고~가 되다</frame>
				</comb_v>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~를 받다</form>
					<frame>Z-이 X-로부터 Y-을 ~를 받다</frame>
					<frame>Z-이 X-로부터 S라고 ~를 받다</frame>
					<frame>Z-이 X-에게서 Y-을 ~를 받다</frame>
					<frame>Z-이 X-에게서 S라고 ~를 받다</frame>
					<frame>Z-이 X-에게 Y-을 ~를 받다</frame>
					<frame>Z-이 X-에게 S라고 ~를 받다</frame>
				</comb_v>
				<comb_v type="npred_vsupvar">
					<form vcompound="no">~를 내리다</form>
					<frame>X-이 Z-에게 W-에대해서 Y-을 ~를 내리다</frame>
					<frame>X-이 Z-에게 W-에대해서 S라고 ~를 내리다</frame>
				</comb_v>
				<!--vcompound: ~하다-->
				<!--vcompound: ~되다-->
				<!--vcompound: ~받다-->
				<max_n_str>X-의 Z-에대한 Y ~</max_n_str>
				<max_n_str>X-의 Z-에대한 S라는 ~</max_n_str>
				<max_n_str>X-의 Y ~</max_n_str>
				<max_n_str>X-의 S라는 ~</max_n_str>
				<max_n_str>Z-에대한 Y ~</max_n_str>
				<max_n_str>Z-에대한 S라는 ~</max_n_str>
				<max_n_str>X-의 ~</max_n_str>
				<max_n_str>Y ~</max_n_str>
				<max_n_str>S라는 ~</max_n_str>
				<sel_rst arg="X">직업인간(판사)|일시적역할인간(재판장)</sel_rst>
				<sel_rst arg="Y">벌|금전(벌금)|처벌|단독행위(징역)|속성값(유죄|무죄)</sel_rst>
				<sel_rst arg="W">범죄및비행|사고|사회갈등</sel_rst>
				<sel_rst arg="Z">인간(피고)</sel_rst>
				<cl type="uni">번</cl>
				<cl type="uni">회</cl>
				<cl type="uni">차례</cl>
				<prt></prt>
				<av></av>
				<pre_d/>
				<pre_n/>
				<s_n></s_n>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/미숙.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>미숙</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/07/07</cre_date>
				<cre_writer>송인욱</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/10</mod_date>
				<mod_writer>박진호</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/11/06</mod_date>
				<mod_writer>서진숙</mod_writer>
				<mod_note>lr수정</mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/07</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note>센스1과 2 반의어 기술</mod_note>
			</mod>
			<note>2003/07/07(송인욱)센스1의 의미부류를 '행위' 범주로 볼 수 있을까?</note>
			<note>센스2는 '미성숙'의 약어형인 듯 한데, 같은 엔트리이므로 일단 동의어 처리함</note>
			<note>2003/10/10(박진호)센스1 합성어 형용사 추가. 합성어 명사에 있던 것 명사연어로 옮김. 센스2 의미부류 수정</note>
		</mnt_grp>
		<morph_grp>
			<org lg="si">未熟</org>
		
			<comp pos="a" type="suffix">~하다</comp>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>이번 비행기 추락 사고는 조종사의 조작 ~으로 인한 것이었다.</eg>
				<eg>그 사고는 아버지의 운전 ~에 기인하는 것이었다.</eg>
				<eg>국회의원들은 외교부 관리들의 협상 ~을 탓했다.</eg>
				<trans>inexperienced</trans>
				<trans>unskilled</trans>
				<trans>half-fledged</trans>
				<trans>poor</trans>
				<sem_class>속성값</sem_class>
				<lr>
					<syn type="kor">서투름</syn>
					<ant type="conv">숙달</ant>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_n type="compound">운전 ~</comb_n>
				<comb_n type="compound">조작 ~</comb_n>
				<av>~으로</av>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>쓰레기 무단 투기는 시민의식의 ~을 단적으로 드러내는 사례이다.</eg>
				<eg>준법정신의 ~은 사회 혼란의 원인이 된다.</eg>
				<trans>immaturity</trans>
				<sem_class>상태</sem_class>
				<lr>
					<syn type="perfect">미성숙</syn>
					<ant type="conv">성숙</ant>
				</lr>
			</sem_grp>
			<syn_grp>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/프라이버시.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>프라이버시</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/09/16</cre_date>
				<cre_writer>서진숙</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/12</mod_date>
				<mod_writer>서진숙</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/10/03</mod_date>
				<mod_writer>김이정</mod_writer>
				<mod_note>의미부류 '권리'를 '상황'으로 수정했으나 검토 요망;동의어 기술</mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/01</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2005/02/15</mod_date>
				<mod_writer>김미현</mod_writer>
				<mod_note>동사 연어 추가</mod_note>
			</mod>
			<add>~를 존중하다|침범하다</add>
		</mnt_grp>
		<morph_grp>
			<org lg="en">privacy</org>
		
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>현대 사회에서는 타인의 ~를 침해해서는 안된다.</eg>
				<trans>privacy</trans>
				<sem_class>상황</sem_class><!--추상적대상?(김이정)-->
				<lr>
					<syn type="etc">사생활</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 존중하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 보호하다</form><!--추가(미현)-->
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~를 침범하다</form>
					<frame></frame>
				</comb_v>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/전면교육.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>전면교육</orth>
	<entry pos="nng_c">
		<mnt_grp>
			<cre>
				<cre_date>2004/07/10</cre_date>
				<cre_writer>전미현</cre_writer>
				<cre_note>정확한 의미를 모르겠음</cre_note>
			</cre>
			<mod>
				<mod_date>2004/0/</mod_date>
				<mod_writer>이성헌</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/25</mod_date>
				<mod_writer>이홍식</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/09/17</mod_date>
				<mod_writer>이민우</mod_writer>
				<mod_note></mod_note>
			</mod>
			<add></add>
		</mnt_grp>
		<see></see>
		<morph_grp>
			<var type="etc"></var>
			<str type="N_N">전면_교육</str>
			<org lg="si">全面敎育</org>
		</morph_grp>
		<idm_grp>
			<idm type="etc"></idm>
		</idm_grp>
		<sense>
			<sem_grp>
				<eg></eg>
				<trans></trans>
				<domain></domain>
				<sem_class>방향성행위</sem_class>
				<lr>
					<syn type="etc"></syn>
					<ant type="etc"></ant>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_aj type="appr"></comb_aj>
				<comb_n type="compound"></comb_n>
				<comb_v type="npred_vsup">
					<form vcompound="yes">~을 하다</form>
					<frame>X-이 Y-를 ~을 하다</frame>
					<frame>X-이 Y-에게 ~을 하다</frame>
				</comb_v>
				<comb_v type="npred_vpred">
					<form vcompound="no">~이 필요하다</form>
				</comb_v>
				<max_n_str>X-의 Y-에 대한 ~</max_n_str>
				<sel_rst arg="X">인간|인간집단</sel_rst>
				<sel_rst arg="Y">인간|인간집단</sel_rst>
				<cl type="uni"></cl>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/체언_상세/아이콘.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007nn.dtd">
<superEntry>
	<orth>아이콘</orth>
	<entry n="1" pos="nng_s">
		<mnt_grp>
			<cre>
				<cre_date>2003/10/20</cre_date>
				<cre_writer>기영인</cre_writer>
			</cre>
			<mod>
				<mod_date>2003/10/20</mod_date>
				<mod_writer>기영인</mod_writer>
			</mod>
			<mod>
				<mod_date>2004/10/31</mod_date>
				<mod_writer>권오희</mod_writer>
				<mod_note>센스1의 동사결합정보 기술</mod_note>
				<mod_note>n_n기술</mod_note>
				<mod_note>n_v 이하 기술</mod_note>
				<mod_note>add옮김</mod_note>
			</mod>
			<mod>
				<mod_date>2004/11/01</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2004/12/28</mod_date>
				<mod_writer>권오희</mod_writer>
				<mod_note>형식검토</mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/29</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>동사결합 추가</mod_note>
				<mod_note>센스 2 추가</mod_note>
			</mod>
			<note>2003/10/20(기영인)센스2의 오표기 '이콘'(센스1은 아님) 별도 표시방법 없음</note>
			<note>센스2 추후 전문영역(종교/그리스정교) 상세화 필요</note>
		</mnt_grp>
		<morph_grp>
			<var type="xx">이콘</var>
			<org lg="en">icon</org>
		
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>이 ~을 누르면 명령이 바로 실행됩니다.</eg>
				<trans>icon</trans>
				<sem_class>기호</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_v type="narg_vpred">
					<form vcompound="no">~이 뜨다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 누르다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 선택하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 클릭하다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~을 만들다</form>
					<frame></frame>
				</comb_v>
				<cl type="uni">개</cl>
				<s_n>S는 ~</s_n>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>심슨 가족은 미키마우스처럼 세계적인 ~으로 자리잡았다.</eg>
				<trans>icon</trans>
				<sem_class>긍정적속성구체물</sem_class>
				<lr>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb_n type="compound">패션 ~</comb_n>
				<comb_v type="narg_vpred">
					<form vcompound="no">~이 되다</form>
					<frame></frame>
				</comb_v>
				<comb_v type="narg_vpred">
					<form vcompound="no">~로 자리잡다</form>
					<frame></frame>
				</comb_v>
				<cl type="temp"></cl>
				<s_n>S는 ~</s_n>
			</syn_grp>
		</sense>
		<sense n="3">
			<sem_grp>
				<eg>정성 들여 금박을 입힌 ~ 속의 성모와 아기 예수는 인자한 모습이었다.</eg>
				<trans>icon</trans>
				<domain>가톨</domain>
				<sem_class>회화</sem_class>
				<lr>
					<syn type="perfect">성상화</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<cl type="uni">개</cl>
				<cl type="uni">점</cl>
				<s_n>S는 ~</s_n>
			</syn_grp>
		</sense>
	</entry>
</superEntry>
