=== HeegyuKim/Buttinsky-Sejong/data/분류사_상세/2007cl.dtd
<!ELEMENT superEntry (orth, entry+)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT entry (mnt_grp, see?, morph_grp?, idm_grp?, sense+)>
<!ATTLIST entry pos (cl) #REQUIRED>

<!ELEMENT mnt_grp (cre, mod*, note*)>
<!ELEMENT cre (cre_date, cre_writer)>
<!ELEMENT cre_date (#PCDATA)>
<!ELEMENT cre_writer (#PCDATA)>
<!ELEMENT mod (mod_date, mod_writer?)>
<!ELEMENT mod_date (#PCDATA)>
<!ELEMENT mod_writer (#PCDATA)>
<!ELEMENT note (#PCDATA)>

<!ELEMENT see (#PCDATA)>

<!ELEMENT morph_grp (var*, str?, org*, symb?, hom?, der*, comp*, metc*, img*)>
<!ELEMENT var (#PCDATA)>
<!ATTLIST var type (xs|xd|xx|abb|lng|spr|etc) #REQUIRED>
<!ELEMENT str (#PCDATA)>
<!ELEMENT org (#PCDATA)>
<!ATTLIST org lg (ar|bu|cam|de|el|en|es|etc|eti|fi|fr|he|id|in|it|ja|ko|la|nl|no|pl|po|pt|ro|ru|si|tai|zh) #REQUIRED>
<!ELEMENT symb (#PCDATA)>
<!ELEMENT hom EMPTY>
<!ATTLIST hom exist (yes) #REQUIRED>
<!ELEMENT der (#PCDATA)>
<!ATTLIST der pos (n|v|a|av) #REQUIRED>
<!ATTLIST der type (suffix|prefix) #REQUIRED>
<!ELEMENT comp (#PCDATA)>
<!ATTLIST comp pos (n|v|a|av) #REQUIRED>
<!ATTLIST comp type (suffix|prefix) #REQUIRED>
<!ELEMENT metc (#PCDATA)>
<!ATTLIST metc pos (n|v|a|av) #REQUIRED>
<!ATTLIST metc type (suffix|prefix|etc) #REQUIRED>
<!ELEMENT img (#PCDATA)>
<!ATTLIST img type (xs|xd|xx|xp) #REQUIRED>

<!ELEMENT idm_grp (idm*)>
<!ELEMENT idm (#PCDATA)>
<!ATTLIST idm type (np|na|nv|da|nc|prv|etc) #REQUIRED>

<!ELEMENT sense (sem_grp?, syn_grp?)>
<!ATTLIST sense n NMTOKEN #REQUIRED>

<!ELEMENT sem_grp (eg+, trans*, domain?, reg?, con*, cl_subtype, rel_n*, lr?)>
<!ELEMENT eg (#PCDATA)>
<!ELEMENT trans (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT reg (#PCDATA)>
<!ELEMENT con (#PCDATA)>
<!ELEMENT cl_subtype (#PCDATA)>
<!ATTLIST cl_subtype type (amt|blk|dgr|div|dst|fqn|grp|kal|knd|lmn|lnt|lrg|odr|prs|pwr|rat|rst|spd|sqr|str|sum|thk|tik|tim|tmp|uni|vct|wdt|wgt) #REQUIRED>
<!ELEMENT rel_n (#PCDATA)>

<!ELEMENT lr (syn*, ant*, rel*)>
<!ELEMENT syn (#PCDATA)>
<!ATTLIST syn type (perfect|sino|kor|honor|de_honor|under|de_under|spoken|de_spoken|vulgar|de_vulgar|etc) #IMPLIED>
<!ELEMENT ant (#PCDATA)>
<!ATTLIST ant type (compl|grad|dir|conv|etc) #IMPLIED>
<!ELEMENT rel (#PCDATA)>

<!ELEMENT syn_grp (flt*, carord?)>
<!ELEMENT flt EMPTY>
<!ATTLIST flt possible (n-mdq-cl|mdq-cl-eui-n|mdq-cl-n|mdq-cl|cl-mdq) #REQUIRED>
<!ELEMENT carord EMPTY>
<!ATTLIST carord car (ko_si|ko|si|etc) #REQUIRED>
<!ATTLIST carord ord (ko_si|ko|si|etc) #REQUIRED>

=== HeegyuKim/Buttinsky-Sejong/data/분류사_상세/두.XML
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007cl.dtd">
<superEntry>
	<orth>두</orth>
	<entry pos="cl">
		<mnt_grp>
			<cre>
				<cre_date>2000/09/30</cre_date>
				<cre_writer>김진해</cre_writer>
			</cre>
			<mod>
				<mod_date>2000/10/18</mod_date>
				<mod_writer>김진해</mod_writer>
			</mod>
			<mod>
				<mod_date>2001/01/10</mod_date>
				<mod_writer>김진해</mod_writer>
			</mod>
			<mod>
				<mod_date>2001/10/15</mod_date>
			</mod>
			<mod>
				<mod_date>2003/07/29</mod_date>
				<mod_writer>김종인</mod_writer>
			</mod>
			<note>상세기술</note>
		</mnt_grp>
		<morph_grp>
			<org lg="si">頭</org>
					<hom exist="yes"/>
		</morph_grp>
		<sense n="1">
			<sem_grp>
				<eg>소 열 ~를 기르다</eg>
				<eg>돼지 다섯 ~를 샀다</eg>
				<cl_subtype type="uni"/>
				<rel_n>말</rel_n>
				<lr>
					<syn type="etc">마리</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<flt possible="n-mdq-cl"/>
				<flt possible="mdq-cl-eui-n"/>
				<carord car="ko" ord="etc"/>
			</syn_grp>
		</sense>
	</entry>
	<entry pos="cl">
		<mnt_grp>
			<cre>
				<cre_date>2001/08/02</cre_date>
				<cre_writer>김종인</cre_writer>
			</cre>
			<mod>
				<mod_date>2001/08/02</mod_date>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">斗</org>
					<hom exist="yes"/>
		</morph_grp>
		<sense n="1">
			<sem_grp>
				<eg>보리 서 ~가 없어서 남의 집에 얹혀 산다</eg>
				<cl_subtype type="blk">10되</cl_subtype>
				<rel_n>곡식</rel_n>
				<lr>
					<syn type="etc">말</syn>
				</lr>
			</sem_grp>
			<syn_grp>
				<flt possible="n-mdq-cl"/>
				<flt possible="mdq-cl-eui-n"/>
				<flt possible="mdq-cl"/>
				<carord car="ko" ord="etc"/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/분류사_상세/에이커.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007cl.dtd">
<superEntry>
	<orth>에이커</orth>
	<entry pos="cl">
		<mnt_grp>
			<cre>
				<cre_date>2001/09/10</cre_date>
				<cre_writer>김종인</cre_writer>
			</cre>
			<mod>
				<mod_date>2001/09/19</mod_date>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="en">acre</org>
			<symb>ac</symb>
		</morph_grp>
		<sense n="1">
			<sem_grp>
				<eg>이 농장은 넓이가 10만 ~쯤 된다</eg>
				<cl_subtype type="sqr"/>
			</sem_grp>
			<syn_grp>
				<flt possible="n-mdq-cl"/>
				<flt possible="mdq-cl-eui-n"/>
				<flt possible="mdq-cl"/>
				<carord car="si" ord="etc"/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>
