=== HeegyuKim/Buttinsky-Sejong/data/어미_상세/2007eomi.dtd
<!ELEMENT superEntry (orth, entry+)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT entry (mnt_grp, head_grp, morph_grp, sem_grp, idm_grp*)>
<!ATTLIST entry n NMTOKEN #IMPLIED>
<!ATTLIST entry pos (e) #REQUIRED>

<!ELEMENT mnt_grp (cre, mod+, note*)>
<!ELEMENT cre (cre_date*, cre_writer*, cre_note*)>
<!ELEMENT cre_date (#PCDATA)>
<!ELEMENT cre_writer (#PCDATA)>
<!ELEMENT cre_note (#PCDATA)>

<!ELEMENT mod (mod_date, mod_writer, mod_note*)>
<!ELEMENT mod_date (#PCDATA)>
<!ELEMENT mod_writer (#PCDATA)>
<!ELEMENT mod_note (#PCDATA)>
<!ELEMENT note (#PCDATA)>

<!ELEMENT head_grp (je_subtype)>
<!ELEMENT je_subtype (#PCDATA)>


<!ELEMENT morph_grp (phn_rst*, mor_rst*, str, var*, note*)>
<!ELEMENT phn_rst (#PCDATA)>
<!ELEMENT mor_rst (#PCDATA)>
<!ELEMENT str (#PCDATA)>
<!ELEMENT var (#PCDATA)>
<!ATTLIST var type (phn|mor|stem|hon|abb|lng|strain|plain|spk_p|spk_n|xs|xd|em_p|em_n|temp|etc) #REQUIRED>

<!ELEMENT sem_grp (sense+)>
<!ELEMENT sense (sem_rep, frn*, fol*, frame*, sel_rst*, own_s, fol_s, eg+)>
<!ATTLIST sense n NMTOKEN #IMPLIED>

<!ELEMENT sem_rep (st, sl, gm)>
<!ELEMENT st (#PCDATA)>
<!ELEMENT sl (#PCDATA)>
<!ELEMENT gm (#PCDATA)>

<!ELEMENT frn (#PCDATA)>
<!ELEMENT fol (#PCDATA)>
<!ELEMENT frame (#PCDATA)>
<!ELEMENT sel_rst (#PCDATA)>
<!ELEMENT own_s (nc, sp)>
<!ELEMENT nc (#PCDATA)>
<!ELEMENT sp (#PCDATA)>

<!ELEMENT fol_s (stt*, prd, rep, sms)>
<!ELEMENT stt (#PCDATA)>
<!ELEMENT prd (#PCDATA)>
<!ELEMENT rep (#PCDATA)>
<!ELEMENT sms (#PCDATA)>
<!ELEMENT eg (#PCDATA)>

<!ELEMENT idm_grp (idm*, idm_eg*)>
<!ELEMENT idm (#PCDATA)>
<!ELEMENT idm_eg (#PCDATA)>

=== HeegyuKim/Buttinsky-Sejong/data/어미_상세/ㄹ런지.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007eomi.dtd">
<superEntry>
	<orth>ㄹ런지</orth>
	<entry n="1" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/09/01</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/17</mod_date>
				<mod_writer>이지영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/10/01</mod_date>
				<mod_writer>박진희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/07></mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>efcs</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>vo</phn_rst>
			<mor_rst>nil</mor_rst>
			<str>nil</str>
			<var type="xs">ㄹ는지</var>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st></st>
					<sl></sl>
					<gm></gm>
				</sem_rep>
				<frn></frn>
				<fol></fol>
				<frame></frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp></sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>비가 올런지 습한 바람이 불기 시작했다.</eg>
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
	<entry n="2" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/09/01</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/17</mod_date>
				<mod_writer>이지영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/11/08</mod_date>
				<mod_writer>박진희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/07></mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>eft</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>vo</phn_rst>
			<mor_rst>nil</mor_rst>
			<str>nil</str>
			<var type="xs">ㄹ는지</var>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st></st>
					<sl></sl>
					<gm></gm>
				</sem_rep>
				<frn></frn>
				<fol></fol>
				<frame></frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp></sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>내일은 비가 올런지?</eg>
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
	<entry n="3" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/09/01</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/17</mod_date>
				<mod_writer>이지영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/11/09</mod_date>
				<mod_writer>박진희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/07></mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>eft</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>vo</phn_rst>
			<mor_rst>nil</mor_rst>
			<str>nil</str>
			<var type="xs">ㄹ는지</var>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st></st>
					<sl></sl>
					<gm></gm>
				</sem_rep>
				<frn></frn>
				<fol></fol>
				<frame></frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp></sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>어떤 사람이 새로 사장이 될런지 누가 알겠어?</eg>
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/어미_상세/으라던지.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007eomi.dtd">
<superEntry>
	<orth>으라던지</orth>
	<entry n="1" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/08/27</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/17</mod_date>
				<mod_writer>이지영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2003/08/10</mod_date>
				<mod_writer>김진형</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/11/17</mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/08</mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>ser</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>cn</phn_rst>
			<mor_rst>nil</mor_rst>
			<str></str>
			<var type="phn">라던지</var>
			<var type="xs">으라든지</var>
			<var type="etc">다던지</var>
			<var type="etc">ㄴ다던지</var>
			<var type="etc">는다던지</var>
			<var type="etc">자던지</var>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st></st>
					<sl></sl>
					<gm></gm>
				</sem_rep>
				<frn></frn>
				<fol></fol>
				<frame></frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp></sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>그 수업 시간에는 학생들에게 책을 읽으라던지 자료를 찾으라던지 하는 요구를 하지 않는다.</eg>
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/어미_상세/노라.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007eomi.dtd">
<superEntry>
	<orth>노라</orth>
	<entry n="1" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/07/22</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/14</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/11/02</mod_date>
				<mod_writer>박진희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/07></mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>eft</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>nil</phn_rst>
			<mor_rst>nil</mor_rst>
			<str>노+라</str>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st>평서</st>
					<sl>하라체</sl>
					<gm>단언</gm>
				</sem_rep>
				<frn>았</frn>
				<frn>았었</frn>
				<frn>겠</frn>
				<fol>nil</fol>
				<frame>Vv-E</frame>
				<frame>ass-E</frame>
				<frame>gss-E</frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp>1인칭</sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>서러움 모두 버리고 나 이제 가노라.</eg>
				<eg>왔노라. 보았노라. 이겼노라.</eg>
				<!--예스러운 표현-->
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
	<entry n="2" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/07/22</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/14</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/08/21</mod_date>
				<mod_writer>박진희</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/07></mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>eft</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>nil</phn_rst>
			<mor_rst>nil</mor_rst>
			<str>노+라</str>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st></st>
					<sl>완형보문</sl>
					<gm>단언의간접인용</gm>
				</sem_rep>
				<frn>았</frn>
				<frn>겠</frn>
				<fol>고</fol>
				<frame>Vv-E</frame>
				<frame>ass-E</frame>
				<frame>gss-E</frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp>1인칭</sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>병사들은 반드시 이기고 돌아오겠노라 맹세하였다.</eg>
				<!--예스러운 표현-->
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/어미_상세/ㄴ다든.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007eomi.dtd">
<superEntry>
	<orth>ㄴ다든</orth>
	<entry n="1" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/07/01</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/14</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/10/21</mod_date>
				<mod_writer>박진희</mod_writer>
				<mod_note>'ㄴ다던'의 비표준형임. 지침서에 따르면 표제어가 될 수 없음.</mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/07></mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>ser</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>vo</phn_rst>
			<mor_rst>nil</mor_rst>
			<str>ㄴ다-(고)_(하)-든</str>
			<var type="xs">ㄴ다던</var>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st></st>
					<sl></sl>
					<gm></gm>
				</sem_rep>
				<frn></frn>
				<fol></fol>
				<frame></frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp></sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>아이들이 오늘 내려온다든?</eg>
				<eg>할머니께서는 언제쯤 오신다든?</eg>
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
	<entry n="2" pos="e">
		<mnt_grp>

			<cre>
				<cre_date>2001/07/01</cre_date>
				<cre_writer>이승희</cre_writer>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/14</mod_date>
				<mod_writer>이광호</mod_writer>
				<mod_note></mod_note>
			</mod>
			<mod>
				<mod_date>2006/10/21</mod_date>
				<mod_writer>박진희</mod_writer>
				<mod_note>'ㄴ다던'의 비표준형임. 지침서에 따르면 표제어가 될 수 없음.</mod_note>
			</mod>
			<mod>
				<mod_date>2007/07/07></mod_date>
				<mod_writer>하신영</mod_writer>
				<mod_note></mod_note>
			</mod>
		</mnt_grp>
		<head_grp>
			<je_subtype>ser</je_subtype>
		</head_grp>
		<morph_grp>
			<phn_rst>vo</phn_rst>
			<mor_rst>nil</mor_rst>
			<str>ㄴ다+든</str>
			<var type="xs">ㄴ다던</var>
		</morph_grp>
		<sem_grp>
			<sense n="1">
				<sem_rep>
					<st></st>
					<sl></sl>
					<gm></gm>
				</sem_rep>
				<frn></frn>
				<fol></fol>
				<frame></frame>
				<sel_rst></sel_rst>
				<own_s>
					<nc></nc>
					<sp></sp>
				</own_s>
				<fol_s>
					<stt></stt>
					<prd></prd>
					<rep></rep>
					<sms></sms>
				</fol_s>
				<eg>도와준다든 사람들은 다 어디로 갔나?</eg>
			</sense>
		</sem_grp>
		<idm_grp>
			
				<idm></idm>
				<idm_eg></idm_eg>
			
		</idm_grp>
	</entry>
</superEntry>
