=== HeegyuKim/Buttinsky-Sejong/data/대명사_상세/2007pron.dtd
<!ELEMENT superEntry (orth, entry+)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT entry (mnt_grp, see?, morph_grp?, idm_grp?, sense+)>
<!ATTLIST entry pos (np|npab) #REQUIRED>

<!ELEMENT mnt_grp (cre, mod*, note*)>
<!ELEMENT cre (cre_date, cre_writer)>
<!ELEMENT cre_date (#PCDATA)>
<!ELEMENT cre_writer (#PCDATA)>
<!ELEMENT mod (mod_date, mod_writer, mod_note*)>
<!ELEMENT mod_date (#PCDATA)>
<!ELEMENT mod_writer (#PCDATA)>
<!ELEMENT mod_note (#PCDATA)>
<!ELEMENT note (#PCDATA)>

<!ELEMENT see (#PCDATA)>

<!ELEMENT morph_grp (var*, str?, org*, symb?, hom?, der*, comp*, metc*, img*)>
<!ELEMENT var (#PCDATA)>
<!ATTLIST var type (xs|xd|xx|abb|lng|spr|etc) #REQUIRED>
<!ELEMENT str (#PCDATA)>
<!ATTLIST str type (N_N|R_N|N_R|R_R|N_Vn|Vn_N|R_Vn|Vn_R|NsN|Vm_N|Am_N|N_S|R_S|V_S|A_S|P_N|P_R|fN_N|N_Nf|fN_Nf|FLW|Ad_N|etc|temp) #REQUIRED>
<!ELEMENT org (#PCDATA)>
<!ATTLIST org lg (si|en|fr|de|ja|it|ru|etc|ko) #REQUIRED>
<!ELEMENT symb (#PCDATA)>

<!ELEMENT hom EMPTY>
<!ATTLIST hom exist (yes) #REQUIRED>
<!ELEMENT der (#PCDATA)>
<!ATTLIST der pos (n|v|a|av) #REQUIRED>
<!ATTLIST der type (suffix|prefix) #REQUIRED>
<!ELEMENT comp (#PCDATA)>
<!ATTLIST comp pos (n|v|a|av) #REQUIRED>
<!ATTLIST comp type (suffix|prefix) #REQUIRED>
<!ELEMENT metc (#PCDATA)>
<!ATTLIST metc pos (n|v|a|av) #REQUIRED>
<!ATTLIST metc type (suffix|prefix|etc) #REQUIRED>
<!ELEMENT img (#PCDATA)>
<!ATTLIST img type (xs|xd|xx|xp) #REQUIRED>

<!ELEMENT idm_grp (idm*)>
<!ELEMENT idm (#PCDATA)>
<!ATTLIST idm type (np|na|nv|da|nc|prv|etc) #REQUIRED>

<!ELEMENT sense (sem_grp?, syn_grp?)>
<!ATTLIST sense n NMTOKEN #REQUIRED>
<!ATTLIST sense sem (1|2|3|interrogative|indefinite|referential|reflexive|reciprocal|etc) #IMPLIED>
<!ATTLIST sense num (singular_plural|singular|plural|etc) #IMPLIED>
<!ATTLIST sense ref (human|thing|place|time|proposition|etc) #IMPLIED>

<!ELEMENT sem_grp (eg+, trans*, domain?, reg*, con*, lr?)>
<!ELEMENT eg (#PCDATA)>
<!ELEMENT trans (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT reg (#PCDATA)>
<!ELEMENT con (#PCDATA)>


<!ELEMENT lr (syn*, ant*, rel*)>
<!ELEMENT syn (#PCDATA)>
<!ATTLIST syn type (perfect|sino|kor|honor|de_honor|under|de_under|spoken|de_spoken|vulgar|de_vulgar|etc) #IMPLIED>
<!ELEMENT ant (#PCDATA)>
<!ATTLIST ant type (compl|grad|dir|conv|etc) #IMPLIED>
<!ELEMENT rel (#PCDATA)>

<!ELEMENT syn_grp (prt*, comb_ida?, pre_d*, pre_n*, s_n*, rep?, etc_cnst?)>
<!ELEMENT prt (#PCDATA)>
<!ATTLIST prt possible (no) #IMPLIED>
<!ELEMENT comb_ida (#PCDATA)>
<!ELEMENT pre_d (#PCDATA)>
<!ATTLIST pre_d yn (no) #IMPLIED>
<!ELEMENT pre_n (#PCDATA)>
<!ATTLIST pre_n yn (no) #IMPLIED>
<!ELEMENT s_n (#PCDATA)>
<!ATTLIST s_n yn (no) #IMPLIED>
<!ELEMENT rep (#PCDATA)>
<!ELEMENT etc_cnst (#PCDATA)>

=== HeegyuKim/Buttinsky-Sejong/data/대명사_상세/저이.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007pron.dtd">
<superEntry>
	<orth>저이</orth>
	<entry pos="np">
		<mnt_grp>
			<cre>
				<cre_date>2000/08/28</cre_date>
				<cre_writer>호정은</cre_writer>
			</cre>
			<mod>
				<mod_date>2001/10/22</mod_date>
				<mod_writer>호정은</mod_writer>
			</mod>
			<mod>
				<mod_date>2003/06/10</mod_date>
				<mod_writer>김종인</mod_writer>
			</mod>
			<mod>
				<mod_date>2006/12/01</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>새 태그 세트에 맞추어 수정</mod_note>
			</mod>
			<note>2001/10/22(호정은)</note>
			<note>2001년 모형에 맞게 수정</note>
		</mnt_grp>
		<morph_grp>
			<str type="etc">저+이</str>
		</morph_grp>
		<sense n="1" sem="3" num="singular" ref="human">
			<sem_grp>
				<eg>~랑 일해 본 적이 있는데 아주 꼼꼼한 사람이더군요</eg>
			</sem_grp>
			<syn_grp>
				<pre_d yn="no"/>
				<pre_n yn="no"/>
			</syn_grp>
		</sense>
		<sense n="2" sem="3" num="singular" ref="human">
			<sem_grp>
				<eg>~가 오늘 왜 저러지?</eg>
				<trans>husband</trans>
				<reg>구어</reg>
				<lr>
					<rel>남편</rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<pre_d yn="no"/>
				<pre_n yn="no"/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/대명사_상세/뭣.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007pron.dtd">
<superEntry>
	<orth>뭣</orth>
	<entry pos="np">
		<mnt_grp>
			<cre>
				<cre_date>2000/08/28</cre_date>
				<cre_writer>호정은</cre_writer>
			</cre>
			<mod>
				<mod_date>2001/10/22</mod_date>
				<mod_writer>호정은</mod_writer>
			</mod>
			<mod>
				<mod_date>2003/06/10</mod_date>
				<mod_writer>김종인</mod_writer>
			</mod>
			<note>2001/10/22(호정은)</note>
			<note>2001년 모형에 맞게 수정</note>
		</mnt_grp>
		<morph_grp>
			<var type="abb">뭐</var>
			<var type="lng">무엇</var>
			<var type="lng">무어</var>
		</morph_grp>
		<idm_grp>
			<idm type="da">~이라고?</idm>
		</idm_grp>
		<sense n="1" sem="interrogative" num="etc" ref="thing">
			<sem_grp>
				<eg>지금 ~ 하느라고 그렇게 바빠?</eg>
				<trans>what</trans>
			</sem_grp>
			<syn_grp>
				<pre_d>그</pre_d>
				<pre_n yn="no"/>
			</syn_grp>
		</sense>
		<sense n="2" sem="indefinite" num="etc" ref="thing">
			<sem_grp>
				<eg>나는 ~보다도 그분의 인품을 존경한다</eg>
			</sem_grp>
			<syn_grp>
				<pre_d>그</pre_d>
				<pre_n yn="no"/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/대명사_상세/후자.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007pron.dtd">
<superEntry>
	<orth>후자</orth>
	<entry pos="np">
		<mnt_grp>
			<cre>
				<cre_date>2001/09/09</cre_date>
				<cre_writer>호정은</cre_writer>
			</cre>
			<mod>
				<mod_date>2001/10/09</mod_date>
				<mod_writer>호정은</mod_writer>
			</mod>
			<mod>
				<mod_date>2003/07/05</mod_date>
				<mod_writer>김종인</mod_writer>
			</mod>
			<mod>
				<mod_date>2006/12/01</mod_date>
				<mod_writer>호정은</mod_writer>
				<mod_note>새 태그 세트에 맞추어 수정</mod_note>
			</mod>
		</mnt_grp>
		<morph_grp>
			<org lg="si">後者</org>
					<hom exist="yes"/>
		</morph_grp>
		<sense n="1" sem="3" num="singular" ref="thing">
			<sem_grp>
				<eg>사람에 따라서는 전자만이 문학의 문제요 ~는 문학 외적인 문제라고 주장한다</eg>
				<trans>the latter</trans>
				<reg>문어</reg>
				<lr>
					<ant type="etc">전자</ant>
				</lr>
			</sem_grp>
			<syn_grp>
				<pre_d yn="no"/>
				<pre_n yn="no"/>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/대명사_상세/니네.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "2007pron.dtd">
<superEntry>
	<orth>니네</orth>
	<entry pos="np">
		<mnt_grp>
			<cre>
				<cre_date>2001/07/22</cre_date>
				<cre_writer>호정은</cre_writer>
			</cre>
			<mod>
				<mod_date>2001/07/26</mod_date>
				<mod_writer>호정은</mod_writer>
			</mod>
			<mod>
				<mod_date>2003/06/30</mod_date>
				<mod_writer>김종인</mod_writer>
			</mod>
		</mnt_grp>
		<see>너네</see>
		<sense n="1">
		</sense>
	</entry>
</superEntry>
