=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/dic_adverb.dtd
<!ELEMENT superEntry (orth, entry+)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT entry (mnt_grp, morph_grp?, idm_grp?, sense+)>
<!ATTLIST entry n NMTOKEN #IMPLIED>
<!ATTLIST entry pos (av) #REQUIRED>		

<!ELEMENT mnt_grp (cre, mod*, note*, see*)>
<!ELEMENT cre (cre_writer*, cre_date*, cre_note*)>
<!ELEMENT cre_writer (#PCDATA)>
<!ELEMENT cre_date (#PCDATA)>
<!ELEMENT cre_note (#PCDATA)>
<!ELEMENT mod (mod_date*, mod_writer*, mod_note*)>
<!ELEMENT mod_date (#PCDATA)>
<!ELEMENT mod_writer (#PCDATA)>
<!ELEMENT mod_note (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT see (#PCDATA)>

<!ELEMENT morph_grp (var*, str?, org*, hom?, der*, comp*, metc*, img*)>
<!ELEMENT var (#PCDATA)>
<!ATTLIST var type (xs|xd|xx|abb|lng|sht|temp) #REQUIRED>
<!ELEMENT str (#PCDATA)>
<!ELEMENT org (#PCDATA)>
<!ATTLIST org lg (si|ko|si_ko|ko_si|ko_si_ko|si_ko_si_ko|ko_si_ko_si|en|gr_si_ko|etc|temp) #REQUIRED>
<!ELEMENT hom EMPTY>
<!ATTLIST hom exist (yes|temp) #REQUIRED>
<!ELEMENT der (#PCDATA)>
<!ATTLIST der pos (n|v|a|av|temp) #REQUIRED>								
<!ELEMENT comp (#PCDATA)>
<!ATTLIST comp pos (n|v|a|av|temp) #REQUIRED>						
<!ELEMENT metc (#PCDATA)>
<!ELEMENT img (#PCDATA)>
<!ATTLIST img type (xt|xl|xg|xc|temp) #REQUIRED>	

<!ELEMENT idm_grp (idm*)>
<!ELEMENT idm (#PCDATA)>
<!ATTLIST idm type (np|na|nv|da|prv|etc|temp) #REQUIRED>

<!ELEMENT sense (sem_grp, syn_grp)>
<!ATTLIST sense n NMTOKEN #IMPLIED>

<!ELEMENT sem_grp (eg+, trans+, domain*, reg*, con*, sem_rep, lr?)>
<!ELEMENT eg (#PCDATA)>
<!ELEMENT trans (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT reg (#PCDATA)>
<!ELEMENT con (#PCDATA)>
<!ELEMENT sem_rep (#PCDATA)>

<!ELEMENT lr (syn*, ant*, hyper*, cohyp*, hypo*, holo*, mero*, rel*)>
<!ELEMENT syn (#PCDATA)>
<!ELEMENT ant (#PCDATA)>
<!ELEMENT hyper (#PCDATA)>
<!ELEMENT cohyp (#PCDATA)>
<!ELEMENT hypo (#PCDATA)>
<!ELEMENT holo (#PCDATA)>
<!ELEMENT mero (#PCDATA)>
<!ELEMENT rel (#PCDATA)>

<!ELEMENT syn_grp (comb*, prt*, argdist*, col*, conc*, distr*)>

<!ELEMENT comb (#PCDATA)>
<!ATTLIST comb pos (v|adj|det|av|n) #REQUIRED>
<!ATTLIST comb exist (yes|no|temp) #REQUIRED>		
<!ELEMENT prt (#PCDATA)>
<!ELEMENT argdist (#PCDATA)>
<!ATTLIST argdist type (np|vp|ap|temp) #REQUIRED>
<!ELEMENT col (#PCDATA)>

<!ELEMENT conc (#PCDATA)>
<!ATTLIST conc type (conj|mood|mod|ta|neg|agr|temp) #REQUIRED>

<!ELEMENT distr (#PCDATA)>

=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/전국적으로.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "dic_adverb.dtd">
<superEntry>
	<orth>전국적으로</orth>
	<entry n="1" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>류병률; 남승호</cre_writer>
				<cre_date>2001/06/11</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/18</mod_date>
			</mod>
			<note></note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<str>전국.적-으로</str>
			<org lg="si">全國的__</org>
			<hom exist="temp"></hom>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>추가 발견도 꾸준히 이어져 ~ 유적지만 열 다섯 군데를 헤아리게 되었다</eg>
				<eg>창업으로 백만장자가 된 교수가 ~ 100여명에 이른다</eg>
				<eg>김씨의 경우처럼 올해 ~ 나타난 냉해는 농민들의 생계를 위협할 수 있다</eg>
				<trans>in all of the country</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/방식</sem_rep>
				<lr>
					<syn>국가적으로</syn>
					<ant>국지적으로</ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<hypo></hypo>
					<holo></holo>
					<mero></mero>
					<rel>전국</rel>
					<rel>전국적</rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~나타나다</comb>
				<comb pos="adj" exist="yes">~유명하다</comb>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt>~는</prt>
				<prt>~도</prt>
				<prt>~만</prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>~S~O~V</distr>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/겅둥.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "dic_adverb.dtd">
<superEntry>
	<orth>겅둥</orth>
	<entry n="1" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>김태경; 남승호</cre_writer>
				<cre_date>2002/04/25</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2002/07/26</mod_date>
			</mod>
			<note>의태</note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<var type="lng">겅둥겅둥</var>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
			<der pos="v">~거리다</der>
			<img type="xt">껑뚱</img>
			<img type="xc">강동</img>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>집값이 한 달 새에 ~ 뛰었다</eg>
				<trans>leaping lightly</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/상징</sem_rep>
				<lr>
					<syn>겅중</syn>
					<syn>껑충</syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~뛰다</comb>
				<comb pos="v" exist="yes">~오르다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>김태경; 남승호</cre_writer>
				<cre_date>2002/04/25</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2002/07/26</mod_date>
			</mod>
			<note>의태</note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
			<comp pos="v">~하다</comp>
			<img type="xt">껑뚱</img>
			<img type="xc">강동</img>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>키가 갑자기 많이 자라서 바지가 ~ 짧아졌다</eg>
				<trans>too short</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/상징</sem_rep>
				<lr>
					<syn>겅중</syn>
					<syn>껑충</syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~짧아지다</comb>
				<comb pos="adj" exist="yes">~짧다</comb>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/간곡히.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "dic_adverb.dtd">
<superEntry>
	<orth>간곡히</orth>
	<entry n="1" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>조지은; 남승호</cre_writer>
				<cre_date>2001/05/12</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/08/27</mod_date>
			</mod>
			<note></note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<str>간곡.히</str>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>영희는 이번 한 번만 용서해 달라고 선생님께 ~ 부탁드렸다</eg>
				<trans>barely</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/방식</sem_rep>
				<lr>
					<syn>간절히</syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<hypo></hypo>
					<holo></holo>
					<mero></mero>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~부탁하다</comb>
				<comb pos="v" exist="yes">~말하다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>S~O~V</distr>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/구시렁구시렁.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "dic_adverb.dtd">
<superEntry>
	<orth>구시렁구시렁</orth>
	<entry n="1" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>김태경; 남승호</cre_writer>
				<cre_date>2002/05/23</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2002/09/18</mod_date>
			</mod>
			<note>의성, 중첩</note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<str>구시렁+구시렁</str>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
			<comp pos="v">~하다</comp>
			<img type="xc">고시랑고시랑</img>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>그는 불만에 찬 표정으로 ~ 중얼대고 있었다</eg>
				<trans>grumbling</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/상징</sem_rep>
				<lr>
					<syn></syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel>구시렁거리다</rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~중얼거리다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>김태경</cre_writer>
				<cre_date>2002/05/23</cre_date>
				<cre_note></cre_note>
			</cre>
			<note>의태, 중 첩</note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<str>구시렁+구시렁</str>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
			<comp pos="v">~하다</comp>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>잠을 못 이루고 밤새 ~ 몸을 뒤척이고 있다</eg>
				<trans>tossing and turning</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/상징</sem_rep>
				<lr>
					<syn>뒤척뒤척</syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel>구시렁거리다</rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~뒤척이다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/가뜩.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "dic_adverb.dtd">
<superEntry>
	<orth>가뜩</orth>
	<entry n="1" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>김태경; 남승호</cre_writer>
				<cre_date>2002/04/07</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2002/07/20</mod_date>
			</mod>
			<note></note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
			<img type="xl">가득</img>
			<img type="xg">그뜩</img>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>컵에 물을 ~ 담아라</eg>
				<trans>fully</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/방식</sem_rep>
				<lr>
					<syn></syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel>가뜩하다</rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~담다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
	</entry>
	<entry n="2" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>김태경; 남승호</cre_writer>
				<cre_date>2002/04/07</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2002/07/26</mod_date>
			</mod>
			<note></note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
			<comp pos="av">~이나</comp>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>~ 장사가 안되는데, 너까지 그만두면 어떻게 하니?</eg>
				<trans>on top of that</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>문장부사/양상부사/강조</sem_rep>
				<lr>
					<syn>가뜩이나</syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="temp"></comb>
				<comb pos="adj" exist="temp"></comb>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj">~-는데</conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/협조없이.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "dic_adverb.dtd">
<superEntry>
	<orth>협조없이</orth>
	<entry n="1" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>류병률; 남승호</cre_writer>
				<cre_date>2001/07/01</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2001/09/08</mod_date>
			</mod>
			<note></note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<str>협조+없.이</str>
			<org lg="si">協助__</org>
			<hom exist="temp"></hom>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>안기부의 직간접적인 지시나 통제 혹은~ 군이 독자적으로 정치공작을 저지른다</eg>
				<trans>without cooperation</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/방식</sem_rep>
				<lr>
					<syn>협력없이</syn>
					<syn>독자적으로</syn>
					<ant>협력하여</ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<hypo></hypo>
					<holo></holo>
					<mero></mero>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~진행하다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>S~O~V</distr>
			</syn_grp>
		</sense>
	</entry>
</superEntry>

=== HeegyuKim/Buttinsky-Sejong/data/부사_상세/홀라당.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>
<!DOCTYPE superEntry SYSTEM "dic_adverb.dtd">
<superEntry>
	<orth>홀라당</orth>
	<entry n="1" pos="av">
		
		<mnt_grp>
			<cre>
				<cre_writer>김태경; 남승호</cre_writer>
				<cre_date>2002/05/17</cre_date>
				<cre_note></cre_note>
			</cre>
			<mod>
				<mod_date>2002/07/26</mod_date>
			</mod>
			<note>의태, 부분중첩</note>
			<see></see>
		</mnt_grp>
		<morph_grp>
			<var type="xs"></var>
			<var type="xd"></var>
			<var type="xx"></var>
			<var type="abb">홀랑</var>
			<org lg="temp"></org>
			<hom exist="temp"></hom>
			<comp pos="n">~알몸</comp>
			<comp pos="n">~대머리</comp>
			<comp pos="n">~속임수</comp>
			<img type="xg">훌러덩</img>
		</morph_grp>
		<idm_grp>
		</idm_grp>
		<sense n="1">
			<sem_grp>
				<eg>바람에 가발이 ~ 벗겨졌다</eg>
				<trans>removing completely</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/상징</sem_rep>
				<lr>
					<syn>홀딱</syn>
					<syn>홀랑</syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~벗다</comb>
				<comb pos="v" exist="yes">~뒤집다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
		<sense n="2">
			<sem_grp>
				<eg>그는 내 감언이설에 ~ 넘어왔다</eg>
				<trans>deeply</trans>
				<trans>madly</trans>
				<domain></domain>
				<reg></reg>
				<con></con>
				
				<sem_rep>성분부사/양태부사/상징</sem_rep>
				<lr>
					<syn>홀랑</syn>
					<syn>홀딱</syn>
					<ant></ant>
					<hyper></hyper>
					<cohyp></cohyp>
					<holo></holo>
					<mero></mero>
					<rel></rel>
				</lr>
			</sem_grp>
			<syn_grp>
				<comb pos="v" exist="yes">~넘어가다</comb>
				<comb pos="v" exist="yes">~반하다</comb>
				<comb pos="adj" exist="no"/>
				<comb pos="det" exist="temp"></comb>
				<comb pos="av" exist="temp"></comb>
				<comb pos="n" exist="temp"></comb>
				<prt></prt>
				<argdist type="np"></argdist>
				<argdist type="vp"></argdist>
				<argdist type="ap"></argdist>
				<col></col>
			
			
				<conc type="conj"></conc>
				<conc type="mood"></conc>
				<conc type="mod"></conc>
				<conc type="ta"></conc>
				<conc type="neg"></conc>
				<conc type="agr"></conc>
				<distr>SO~V</distr>
			</syn_grp>
		</sense>
	</entry>
</superEntry>
